# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui5.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color : #5500FF;")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Player1_name = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Player1_name.setFont(font)
        self.Player1_name.setObjectName("Player1_name")
        self.verticalLayout_3.addWidget(self.Player1_name)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setText("")
        self.checkBox_6.setTristate(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox_6)
        self.gridLayout.addWidget(self.checkBox_6, 5, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setText("")
        self.checkBox_13.setTristate(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.buttonGroup.addButton(self.checkBox_13)
        self.gridLayout.addWidget(self.checkBox_13, 1, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setText("")
        self.checkBox_5.setTristate(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.buttonGroup.addButton(self.checkBox_5)
        self.gridLayout.addWidget(self.checkBox_5, 4, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setText("")
        self.checkBox_7.setTristate(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.buttonGroup.addButton(self.checkBox_7)
        self.gridLayout.addWidget(self.checkBox_7, 6, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setText("")
        self.checkBox_8.setTristate(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.buttonGroup.addButton(self.checkBox_8)
        self.gridLayout.addWidget(self.checkBox_8, 7, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setText("")
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.buttonGroup.addButton(self.checkBox_3)
        self.gridLayout.addWidget(self.checkBox_3, 2, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setText("")
        self.checkBox_4.setTristate(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.buttonGroup.addButton(self.checkBox_4)
        self.gridLayout.addWidget(self.checkBox_4, 3, 1, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_30.setText("")
        self.checkBox_30.setTristate(True)
        self.checkBox_30.setObjectName("checkBox_30")
        self.buttonGroup.addButton(self.checkBox_30)
        self.gridLayout.addWidget(self.checkBox_30, 3, 2, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_31.setText("")
        self.checkBox_31.setTristate(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.buttonGroup.addButton(self.checkBox_31)
        self.gridLayout.addWidget(self.checkBox_31, 3, 3, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_32.setText("")
        self.checkBox_32.setTristate(True)
        self.checkBox_32.setObjectName("checkBox_32")
        self.buttonGroup.addButton(self.checkBox_32)
        self.gridLayout.addWidget(self.checkBox_32, 3, 4, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_33.setText("")
        self.checkBox_33.setTristate(True)
        self.checkBox_33.setObjectName("checkBox_33")
        self.buttonGroup.addButton(self.checkBox_33)
        self.gridLayout.addWidget(self.checkBox_33, 3, 5, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_34.setText("")
        self.checkBox_34.setTristate(True)
        self.checkBox_34.setObjectName("checkBox_34")
        self.buttonGroup.addButton(self.checkBox_34)
        self.gridLayout.addWidget(self.checkBox_34, 3, 6, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_35.setText("")
        self.checkBox_35.setTristate(True)
        self.checkBox_35.setObjectName("checkBox_35")
        self.buttonGroup.addButton(self.checkBox_35)
        self.gridLayout.addWidget(self.checkBox_35, 3, 7, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_36.setText("")
        self.checkBox_36.setTristate(True)
        self.checkBox_36.setObjectName("checkBox_36")
        self.buttonGroup.addButton(self.checkBox_36)
        self.gridLayout.addWidget(self.checkBox_36, 3, 8, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_37.setText("")
        self.checkBox_37.setTristate(True)
        self.checkBox_37.setObjectName("checkBox_37")
        self.buttonGroup.addButton(self.checkBox_37)
        self.gridLayout.addWidget(self.checkBox_37, 3, 9, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_38.setText("")
        self.checkBox_38.setTristate(True)
        self.checkBox_38.setObjectName("checkBox_38")
        self.buttonGroup.addButton(self.checkBox_38)
        self.gridLayout.addWidget(self.checkBox_38, 3, 10, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_39.setText("")
        self.checkBox_39.setTristate(True)
        self.checkBox_39.setObjectName("checkBox_39")
        self.buttonGroup.addButton(self.checkBox_39)
        self.gridLayout.addWidget(self.checkBox_39, 4, 2, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_40.setText("")
        self.checkBox_40.setTristate(True)
        self.checkBox_40.setObjectName("checkBox_40")
        self.buttonGroup.addButton(self.checkBox_40)
        self.gridLayout.addWidget(self.checkBox_40, 4, 3, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_41.setText("")
        self.checkBox_41.setTristate(True)
        self.checkBox_41.setObjectName("checkBox_41")
        self.buttonGroup.addButton(self.checkBox_41)
        self.gridLayout.addWidget(self.checkBox_41, 4, 4, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_42.setText("")
        self.checkBox_42.setTristate(True)
        self.checkBox_42.setObjectName("checkBox_42")
        self.buttonGroup.addButton(self.checkBox_42)
        self.gridLayout.addWidget(self.checkBox_42, 4, 5, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_43.setText("")
        self.checkBox_43.setTristate(True)
        self.checkBox_43.setObjectName("checkBox_43")
        self.buttonGroup.addButton(self.checkBox_43)
        self.gridLayout.addWidget(self.checkBox_43, 4, 6, 1, 1)
        self.checkBox_44 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_44.setText("")
        self.checkBox_44.setTristate(True)
        self.checkBox_44.setObjectName("checkBox_44")
        self.buttonGroup.addButton(self.checkBox_44)
        self.gridLayout.addWidget(self.checkBox_44, 4, 7, 1, 1)
        self.checkBox_45 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_45.setText("")
        self.checkBox_45.setTristate(True)
        self.checkBox_45.setObjectName("checkBox_45")
        self.buttonGroup.addButton(self.checkBox_45)
        self.gridLayout.addWidget(self.checkBox_45, 4, 8, 1, 1)
        self.checkBox_46 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_46.setText("")
        self.checkBox_46.setTristate(True)
        self.checkBox_46.setObjectName("checkBox_46")
        self.buttonGroup.addButton(self.checkBox_46)
        self.gridLayout.addWidget(self.checkBox_46, 4, 9, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_47.setText("")
        self.checkBox_47.setTristate(True)
        self.checkBox_47.setObjectName("checkBox_47")
        self.buttonGroup.addButton(self.checkBox_47)
        self.gridLayout.addWidget(self.checkBox_47, 4, 10, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setText("")
        self.checkBox_14.setTristate(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.buttonGroup.addButton(self.checkBox_14)
        self.gridLayout.addWidget(self.checkBox_14, 1, 4, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setText("")
        self.checkBox_15.setTristate(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.buttonGroup.addButton(self.checkBox_15)
        self.gridLayout.addWidget(self.checkBox_15, 1, 5, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_16.setText("")
        self.checkBox_16.setTristate(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.buttonGroup.addButton(self.checkBox_16)
        self.gridLayout.addWidget(self.checkBox_16, 1, 6, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_17.setText("")
        self.checkBox_17.setTristate(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.buttonGroup.addButton(self.checkBox_17)
        self.gridLayout.addWidget(self.checkBox_17, 1, 7, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_18.setText("")
        self.checkBox_18.setTristate(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.buttonGroup.addButton(self.checkBox_18)
        self.gridLayout.addWidget(self.checkBox_18, 1, 8, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_19.setText("")
        self.checkBox_19.setTristate(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.buttonGroup.addButton(self.checkBox_19)
        self.gridLayout.addWidget(self.checkBox_19, 1, 9, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_20.setText("")
        self.checkBox_20.setTristate(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.buttonGroup.addButton(self.checkBox_20)
        self.gridLayout.addWidget(self.checkBox_20, 1, 10, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_21.setText("")
        self.checkBox_21.setTristate(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.buttonGroup.addButton(self.checkBox_21)
        self.gridLayout.addWidget(self.checkBox_21, 2, 2, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_22.setText("")
        self.checkBox_22.setTristate(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.buttonGroup.addButton(self.checkBox_22)
        self.gridLayout.addWidget(self.checkBox_22, 2, 3, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_23.setText("")
        self.checkBox_23.setTristate(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.buttonGroup.addButton(self.checkBox_23)
        self.gridLayout.addWidget(self.checkBox_23, 2, 4, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_24.setText("")
        self.checkBox_24.setTristate(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.buttonGroup.addButton(self.checkBox_24)
        self.gridLayout.addWidget(self.checkBox_24, 2, 5, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_25.setText("")
        self.checkBox_25.setTristate(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.buttonGroup.addButton(self.checkBox_25)
        self.gridLayout.addWidget(self.checkBox_25, 2, 6, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_26.setText("")
        self.checkBox_26.setTristate(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.buttonGroup.addButton(self.checkBox_26)
        self.gridLayout.addWidget(self.checkBox_26, 2, 7, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_27.setText("")
        self.checkBox_27.setTristate(True)
        self.checkBox_27.setObjectName("checkBox_27")
        self.buttonGroup.addButton(self.checkBox_27)
        self.gridLayout.addWidget(self.checkBox_27, 2, 8, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_28.setText("")
        self.checkBox_28.setTristate(True)
        self.checkBox_28.setObjectName("checkBox_28")
        self.buttonGroup.addButton(self.checkBox_28)
        self.gridLayout.addWidget(self.checkBox_28, 2, 9, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_29.setText("")
        self.checkBox_29.setTristate(True)
        self.checkBox_29.setObjectName("checkBox_29")
        self.buttonGroup.addButton(self.checkBox_29)
        self.gridLayout.addWidget(self.checkBox_29, 2, 10, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(16, 16))
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonGroup.addButton(self.checkBox)
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setText("")
        self.checkBox_9.setTristate(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.buttonGroup.addButton(self.checkBox_9)
        self.gridLayout.addWidget(self.checkBox_9, 8, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setText("")
        self.checkBox_10.setTristate(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.buttonGroup.addButton(self.checkBox_10)
        self.gridLayout.addWidget(self.checkBox_10, 9, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setText("")
        self.checkBox_11.setTristate(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.buttonGroup.addButton(self.checkBox_11)
        self.gridLayout.addWidget(self.checkBox_11, 10, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setText("")
        self.checkBox_12.setTristate(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.buttonGroup.addButton(self.checkBox_12)
        self.gridLayout.addWidget(self.checkBox_12, 1, 2, 1, 1)
        self.checkBox_94 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_94.setText("")
        self.checkBox_94.setTristate(True)
        self.checkBox_94.setObjectName("checkBox_94")
        self.buttonGroup.addButton(self.checkBox_94)
        self.gridLayout.addWidget(self.checkBox_94, 5, 2, 1, 1)
        self.checkBox_95 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_95.setText("")
        self.checkBox_95.setTristate(True)
        self.checkBox_95.setObjectName("checkBox_95")
        self.buttonGroup.addButton(self.checkBox_95)
        self.gridLayout.addWidget(self.checkBox_95, 5, 3, 1, 1)
        self.checkBox_96 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_96.setText("")
        self.checkBox_96.setTristate(True)
        self.checkBox_96.setObjectName("checkBox_96")
        self.buttonGroup.addButton(self.checkBox_96)
        self.gridLayout.addWidget(self.checkBox_96, 5, 4, 1, 1)
        self.checkBox_97 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_97.setText("")
        self.checkBox_97.setTristate(True)
        self.checkBox_97.setObjectName("checkBox_97")
        self.buttonGroup.addButton(self.checkBox_97)
        self.gridLayout.addWidget(self.checkBox_97, 5, 5, 1, 1)
        self.checkBox_98 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_98.setText("")
        self.checkBox_98.setTristate(True)
        self.checkBox_98.setObjectName("checkBox_98")
        self.buttonGroup.addButton(self.checkBox_98)
        self.gridLayout.addWidget(self.checkBox_98, 5, 6, 1, 1)
        self.checkBox_99 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_99.setText("")
        self.checkBox_99.setTristate(True)
        self.checkBox_99.setObjectName("checkBox_99")
        self.buttonGroup.addButton(self.checkBox_99)
        self.gridLayout.addWidget(self.checkBox_99, 5, 7, 1, 1)
        self.checkBox_100 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_100.setText("")
        self.checkBox_100.setTristate(True)
        self.checkBox_100.setObjectName("checkBox_100")
        self.buttonGroup.addButton(self.checkBox_100)
        self.gridLayout.addWidget(self.checkBox_100, 5, 8, 1, 1)
        self.checkBox_101 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_101.setText("")
        self.checkBox_101.setTristate(True)
        self.checkBox_101.setObjectName("checkBox_101")
        self.buttonGroup.addButton(self.checkBox_101)
        self.gridLayout.addWidget(self.checkBox_101, 5, 9, 1, 1)
        self.checkBox_102 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_102.setText("")
        self.checkBox_102.setTristate(True)
        self.checkBox_102.setObjectName("checkBox_102")
        self.buttonGroup.addButton(self.checkBox_102)
        self.gridLayout.addWidget(self.checkBox_102, 5, 10, 1, 1)
        self.checkBox_103 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_103.setText("")
        self.checkBox_103.setTristate(True)
        self.checkBox_103.setObjectName("checkBox_103")
        self.buttonGroup.addButton(self.checkBox_103)
        self.gridLayout.addWidget(self.checkBox_103, 6, 2, 1, 1)
        self.checkBox_104 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_104.setText("")
        self.checkBox_104.setTristate(True)
        self.checkBox_104.setObjectName("checkBox_104")
        self.buttonGroup.addButton(self.checkBox_104)
        self.gridLayout.addWidget(self.checkBox_104, 6, 3, 1, 1)
        self.checkBox_105 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_105.setText("")
        self.checkBox_105.setTristate(True)
        self.checkBox_105.setObjectName("checkBox_105")
        self.buttonGroup.addButton(self.checkBox_105)
        self.gridLayout.addWidget(self.checkBox_105, 6, 4, 1, 1)
        self.checkBox_106 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_106.setText("")
        self.checkBox_106.setTristate(True)
        self.checkBox_106.setObjectName("checkBox_106")
        self.buttonGroup.addButton(self.checkBox_106)
        self.gridLayout.addWidget(self.checkBox_106, 6, 5, 1, 1)
        self.checkBox_107 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_107.setText("")
        self.checkBox_107.setTristate(True)
        self.checkBox_107.setObjectName("checkBox_107")
        self.buttonGroup.addButton(self.checkBox_107)
        self.gridLayout.addWidget(self.checkBox_107, 6, 6, 1, 1)
        self.checkBox_108 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_108.setText("")
        self.checkBox_108.setTristate(True)
        self.checkBox_108.setObjectName("checkBox_108")
        self.buttonGroup.addButton(self.checkBox_108)
        self.gridLayout.addWidget(self.checkBox_108, 6, 7, 1, 1)
        self.checkBox_109 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_109.setText("")
        self.checkBox_109.setTristate(True)
        self.checkBox_109.setObjectName("checkBox_109")
        self.buttonGroup.addButton(self.checkBox_109)
        self.gridLayout.addWidget(self.checkBox_109, 6, 8, 1, 1)
        self.checkBox_110 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_110.setText("")
        self.checkBox_110.setTristate(True)
        self.checkBox_110.setObjectName("checkBox_110")
        self.buttonGroup.addButton(self.checkBox_110)
        self.gridLayout.addWidget(self.checkBox_110, 6, 9, 1, 1)
        self.checkBox_111 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_111.setText("")
        self.checkBox_111.setTristate(True)
        self.checkBox_111.setObjectName("checkBox_111")
        self.buttonGroup.addButton(self.checkBox_111)
        self.gridLayout.addWidget(self.checkBox_111, 6, 10, 1, 1)
        self.checkBox_112 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_112.setText("")
        self.checkBox_112.setTristate(True)
        self.checkBox_112.setObjectName("checkBox_112")
        self.buttonGroup.addButton(self.checkBox_112)
        self.gridLayout.addWidget(self.checkBox_112, 7, 2, 1, 1)
        self.checkBox_113 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_113.setText("")
        self.checkBox_113.setTristate(True)
        self.checkBox_113.setObjectName("checkBox_113")
        self.buttonGroup.addButton(self.checkBox_113)
        self.gridLayout.addWidget(self.checkBox_113, 7, 3, 1, 1)
        self.checkBox_114 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_114.setText("")
        self.checkBox_114.setTristate(True)
        self.checkBox_114.setObjectName("checkBox_114")
        self.buttonGroup.addButton(self.checkBox_114)
        self.gridLayout.addWidget(self.checkBox_114, 7, 4, 1, 1)
        self.checkBox_115 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_115.setText("")
        self.checkBox_115.setTristate(True)
        self.checkBox_115.setObjectName("checkBox_115")
        self.buttonGroup.addButton(self.checkBox_115)
        self.gridLayout.addWidget(self.checkBox_115, 7, 5, 1, 1)
        self.checkBox_116 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_116.setText("")
        self.checkBox_116.setTristate(True)
        self.checkBox_116.setObjectName("checkBox_116")
        self.buttonGroup.addButton(self.checkBox_116)
        self.gridLayout.addWidget(self.checkBox_116, 7, 6, 1, 1)
        self.checkBox_117 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_117.setText("")
        self.checkBox_117.setTristate(True)
        self.checkBox_117.setObjectName("checkBox_117")
        self.buttonGroup.addButton(self.checkBox_117)
        self.gridLayout.addWidget(self.checkBox_117, 7, 7, 1, 1)
        self.checkBox_118 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_118.setText("")
        self.checkBox_118.setTristate(True)
        self.checkBox_118.setObjectName("checkBox_118")
        self.buttonGroup.addButton(self.checkBox_118)
        self.gridLayout.addWidget(self.checkBox_118, 7, 8, 1, 1)
        self.checkBox_119 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_119.setText("")
        self.checkBox_119.setTristate(True)
        self.checkBox_119.setObjectName("checkBox_119")
        self.buttonGroup.addButton(self.checkBox_119)
        self.gridLayout.addWidget(self.checkBox_119, 7, 9, 1, 1)
        self.checkBox_120 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_120.setText("")
        self.checkBox_120.setTristate(True)
        self.checkBox_120.setObjectName("checkBox_120")
        self.buttonGroup.addButton(self.checkBox_120)
        self.gridLayout.addWidget(self.checkBox_120, 7, 10, 1, 1)
        self.checkBox_121 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_121.setText("")
        self.checkBox_121.setTristate(True)
        self.checkBox_121.setObjectName("checkBox_121")
        self.buttonGroup.addButton(self.checkBox_121)
        self.gridLayout.addWidget(self.checkBox_121, 8, 2, 1, 1)
        self.checkBox_122 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_122.setText("")
        self.checkBox_122.setTristate(True)
        self.checkBox_122.setObjectName("checkBox_122")
        self.buttonGroup.addButton(self.checkBox_122)
        self.gridLayout.addWidget(self.checkBox_122, 8, 3, 1, 1)
        self.checkBox_123 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_123.setText("")
        self.checkBox_123.setTristate(True)
        self.checkBox_123.setObjectName("checkBox_123")
        self.buttonGroup.addButton(self.checkBox_123)
        self.gridLayout.addWidget(self.checkBox_123, 8, 4, 1, 1)
        self.checkBox_124 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_124.setText("")
        self.checkBox_124.setTristate(True)
        self.checkBox_124.setObjectName("checkBox_124")
        self.buttonGroup.addButton(self.checkBox_124)
        self.gridLayout.addWidget(self.checkBox_124, 8, 5, 1, 1)
        self.checkBox_125 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_125.setText("")
        self.checkBox_125.setTristate(True)
        self.checkBox_125.setObjectName("checkBox_125")
        self.buttonGroup.addButton(self.checkBox_125)
        self.gridLayout.addWidget(self.checkBox_125, 8, 6, 1, 1)
        self.checkBox_126 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_126.setText("")
        self.checkBox_126.setTristate(True)
        self.checkBox_126.setObjectName("checkBox_126")
        self.buttonGroup.addButton(self.checkBox_126)
        self.gridLayout.addWidget(self.checkBox_126, 8, 7, 1, 1)
        self.checkBox_127 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_127.setText("")
        self.checkBox_127.setTristate(True)
        self.checkBox_127.setObjectName("checkBox_127")
        self.buttonGroup.addButton(self.checkBox_127)
        self.gridLayout.addWidget(self.checkBox_127, 8, 8, 1, 1)
        self.checkBox_128 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_128.setText("")
        self.checkBox_128.setTristate(True)
        self.checkBox_128.setObjectName("checkBox_128")
        self.buttonGroup.addButton(self.checkBox_128)
        self.gridLayout.addWidget(self.checkBox_128, 8, 9, 1, 1)
        self.checkBox_129 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_129.setText("")
        self.checkBox_129.setTristate(True)
        self.checkBox_129.setObjectName("checkBox_129")
        self.buttonGroup.addButton(self.checkBox_129)
        self.gridLayout.addWidget(self.checkBox_129, 8, 10, 1, 1)
        self.checkBox_130 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_130.setText("")
        self.checkBox_130.setTristate(True)
        self.checkBox_130.setObjectName("checkBox_130")
        self.buttonGroup.addButton(self.checkBox_130)
        self.gridLayout.addWidget(self.checkBox_130, 9, 2, 1, 1)
        self.checkBox_131 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_131.setText("")
        self.checkBox_131.setTristate(True)
        self.checkBox_131.setObjectName("checkBox_131")
        self.buttonGroup.addButton(self.checkBox_131)
        self.gridLayout.addWidget(self.checkBox_131, 9, 3, 1, 1)
        self.checkBox_132 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_132.setText("")
        self.checkBox_132.setTristate(True)
        self.checkBox_132.setObjectName("checkBox_132")
        self.buttonGroup.addButton(self.checkBox_132)
        self.gridLayout.addWidget(self.checkBox_132, 9, 4, 1, 1)
        self.checkBox_133 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_133.setText("")
        self.checkBox_133.setTristate(True)
        self.checkBox_133.setObjectName("checkBox_133")
        self.buttonGroup.addButton(self.checkBox_133)
        self.gridLayout.addWidget(self.checkBox_133, 9, 5, 1, 1)
        self.checkBox_134 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_134.setText("")
        self.checkBox_134.setTristate(True)
        self.checkBox_134.setObjectName("checkBox_134")
        self.buttonGroup.addButton(self.checkBox_134)
        self.gridLayout.addWidget(self.checkBox_134, 9, 6, 1, 1)
        self.checkBox_135 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_135.setText("")
        self.checkBox_135.setTristate(True)
        self.checkBox_135.setObjectName("checkBox_135")
        self.buttonGroup.addButton(self.checkBox_135)
        self.gridLayout.addWidget(self.checkBox_135, 9, 7, 1, 1)
        self.checkBox_136 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_136.setText("")
        self.checkBox_136.setTristate(True)
        self.checkBox_136.setObjectName("checkBox_136")
        self.buttonGroup.addButton(self.checkBox_136)
        self.gridLayout.addWidget(self.checkBox_136, 9, 8, 1, 1)
        self.checkBox_137 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_137.setText("")
        self.checkBox_137.setTristate(True)
        self.checkBox_137.setObjectName("checkBox_137")
        self.buttonGroup.addButton(self.checkBox_137)
        self.gridLayout.addWidget(self.checkBox_137, 9, 9, 1, 1)
        self.checkBox_138 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_138.setText("")
        self.checkBox_138.setTristate(True)
        self.checkBox_138.setObjectName("checkBox_138")
        self.buttonGroup.addButton(self.checkBox_138)
        self.gridLayout.addWidget(self.checkBox_138, 9, 10, 1, 1)
        self.checkBox_139 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_139.setText("")
        self.checkBox_139.setTristate(True)
        self.checkBox_139.setObjectName("checkBox_139")
        self.buttonGroup.addButton(self.checkBox_139)
        self.gridLayout.addWidget(self.checkBox_139, 10, 2, 1, 1)
        self.checkBox_140 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_140.setText("")
        self.checkBox_140.setTristate(True)
        self.checkBox_140.setObjectName("checkBox_140")
        self.buttonGroup.addButton(self.checkBox_140)
        self.gridLayout.addWidget(self.checkBox_140, 10, 3, 1, 1)
        self.checkBox_141 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_141.setText("")
        self.checkBox_141.setTristate(True)
        self.checkBox_141.setObjectName("checkBox_141")
        self.buttonGroup.addButton(self.checkBox_141)
        self.gridLayout.addWidget(self.checkBox_141, 10, 4, 1, 1)
        self.checkBox_142 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_142.setText("")
        self.checkBox_142.setTristate(True)
        self.checkBox_142.setObjectName("checkBox_142")
        self.buttonGroup.addButton(self.checkBox_142)
        self.gridLayout.addWidget(self.checkBox_142, 10, 5, 1, 1)
        self.checkBox_143 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_143.setText("")
        self.checkBox_143.setTristate(True)
        self.checkBox_143.setObjectName("checkBox_143")
        self.buttonGroup.addButton(self.checkBox_143)
        self.gridLayout.addWidget(self.checkBox_143, 10, 6, 1, 1)
        self.checkBox_144 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_144.setText("")
        self.checkBox_144.setTristate(True)
        self.checkBox_144.setObjectName("checkBox_144")
        self.buttonGroup.addButton(self.checkBox_144)
        self.gridLayout.addWidget(self.checkBox_144, 10, 7, 1, 1)
        self.checkBox_145 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_145.setText("")
        self.checkBox_145.setTristate(True)
        self.checkBox_145.setObjectName("checkBox_145")
        self.buttonGroup.addButton(self.checkBox_145)
        self.gridLayout.addWidget(self.checkBox_145, 10, 8, 1, 1)
        self.checkBox_146 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_146.setText("")
        self.checkBox_146.setTristate(True)
        self.checkBox_146.setObjectName("checkBox_146")
        self.buttonGroup.addButton(self.checkBox_146)
        self.gridLayout.addWidget(self.checkBox_146, 10, 9, 1, 1)
        self.checkBox_147 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_147.setText("")
        self.checkBox_147.setTristate(True)
        self.checkBox_147.setObjectName("checkBox_147")
        self.buttonGroup.addButton(self.checkBox_147)
        self.gridLayout.addWidget(self.checkBox_147, 10, 10, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 9, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 10, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Player2_name = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Player2_name.setFont(font)
        self.Player2_name.setObjectName("Player2_name")
        self.verticalLayout_4.addWidget(self.Player2_name)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_48 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_48.setText("")
        self.checkBox_48.setTristate(True)
        self.checkBox_48.setObjectName("checkBox_48")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.checkBox_48)
        self.gridLayout_2.addWidget(self.checkBox_48, 5, 1, 1, 1)
        self.checkBox_49 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_49.setText("")
        self.checkBox_49.setTristate(True)
        self.checkBox_49.setObjectName("checkBox_49")
        self.buttonGroup_2.addButton(self.checkBox_49)
        self.gridLayout_2.addWidget(self.checkBox_49, 1, 3, 1, 1)
        self.checkBox_50 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_50.setText("")
        self.checkBox_50.setTristate(True)
        self.checkBox_50.setObjectName("checkBox_50")
        self.buttonGroup_2.addButton(self.checkBox_50)
        self.gridLayout_2.addWidget(self.checkBox_50, 4, 1, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_51.setText("")
        self.checkBox_51.setTristate(True)
        self.checkBox_51.setObjectName("checkBox_51")
        self.buttonGroup_2.addButton(self.checkBox_51)
        self.gridLayout_2.addWidget(self.checkBox_51, 6, 1, 1, 1)
        self.checkBox_52 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_52.setText("")
        self.checkBox_52.setTristate(True)
        self.checkBox_52.setObjectName("checkBox_52")
        self.buttonGroup_2.addButton(self.checkBox_52)
        self.gridLayout_2.addWidget(self.checkBox_52, 7, 1, 1, 1)
        self.checkBox_53 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_53.setText("")
        self.checkBox_53.setTristate(True)
        self.checkBox_53.setObjectName("checkBox_53")
        self.buttonGroup_2.addButton(self.checkBox_53)
        self.gridLayout_2.addWidget(self.checkBox_53, 2, 1, 1, 1)
        self.checkBox_54 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_54.setText("")
        self.checkBox_54.setTristate(True)
        self.checkBox_54.setObjectName("checkBox_54")
        self.buttonGroup_2.addButton(self.checkBox_54)
        self.gridLayout_2.addWidget(self.checkBox_54, 3, 1, 1, 1)
        self.checkBox_55 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_55.setText("")
        self.checkBox_55.setTristate(True)
        self.checkBox_55.setObjectName("checkBox_55")
        self.buttonGroup_2.addButton(self.checkBox_55)
        self.gridLayout_2.addWidget(self.checkBox_55, 3, 2, 1, 1)
        self.checkBox_56 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_56.setText("")
        self.checkBox_56.setTristate(True)
        self.checkBox_56.setObjectName("checkBox_56")
        self.buttonGroup_2.addButton(self.checkBox_56)
        self.gridLayout_2.addWidget(self.checkBox_56, 3, 3, 1, 1)
        self.checkBox_57 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_57.setText("")
        self.checkBox_57.setTristate(True)
        self.checkBox_57.setObjectName("checkBox_57")
        self.buttonGroup_2.addButton(self.checkBox_57)
        self.gridLayout_2.addWidget(self.checkBox_57, 3, 4, 1, 1)
        self.checkBox_58 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_58.setText("")
        self.checkBox_58.setTristate(True)
        self.checkBox_58.setObjectName("checkBox_58")
        self.buttonGroup_2.addButton(self.checkBox_58)
        self.gridLayout_2.addWidget(self.checkBox_58, 3, 5, 1, 1)
        self.checkBox_59 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_59.setText("")
        self.checkBox_59.setTristate(True)
        self.checkBox_59.setObjectName("checkBox_59")
        self.buttonGroup_2.addButton(self.checkBox_59)
        self.gridLayout_2.addWidget(self.checkBox_59, 3, 6, 1, 1)
        self.checkBox_60 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_60.setText("")
        self.checkBox_60.setTristate(True)
        self.checkBox_60.setObjectName("checkBox_60")
        self.buttonGroup_2.addButton(self.checkBox_60)
        self.gridLayout_2.addWidget(self.checkBox_60, 3, 7, 1, 1)
        self.checkBox_61 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_61.setText("")
        self.checkBox_61.setTristate(True)
        self.checkBox_61.setObjectName("checkBox_61")
        self.buttonGroup_2.addButton(self.checkBox_61)
        self.gridLayout_2.addWidget(self.checkBox_61, 3, 8, 1, 1)
        self.checkBox_62 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_62.setText("")
        self.checkBox_62.setTristate(True)
        self.checkBox_62.setObjectName("checkBox_62")
        self.buttonGroup_2.addButton(self.checkBox_62)
        self.gridLayout_2.addWidget(self.checkBox_62, 3, 9, 1, 1)
        self.checkBox_63 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_63.setText("")
        self.checkBox_63.setTristate(True)
        self.checkBox_63.setObjectName("checkBox_63")
        self.buttonGroup_2.addButton(self.checkBox_63)
        self.gridLayout_2.addWidget(self.checkBox_63, 3, 10, 1, 1)
        self.checkBox_64 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_64.setText("")
        self.checkBox_64.setTristate(True)
        self.checkBox_64.setObjectName("checkBox_64")
        self.buttonGroup_2.addButton(self.checkBox_64)
        self.gridLayout_2.addWidget(self.checkBox_64, 4, 2, 1, 1)
        self.checkBox_65 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_65.setText("")
        self.checkBox_65.setTristate(True)
        self.checkBox_65.setObjectName("checkBox_65")
        self.buttonGroup_2.addButton(self.checkBox_65)
        self.gridLayout_2.addWidget(self.checkBox_65, 4, 3, 1, 1)
        self.checkBox_66 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_66.setText("")
        self.checkBox_66.setTristate(True)
        self.checkBox_66.setObjectName("checkBox_66")
        self.buttonGroup_2.addButton(self.checkBox_66)
        self.gridLayout_2.addWidget(self.checkBox_66, 4, 4, 1, 1)
        self.checkBox_67 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_67.setText("")
        self.checkBox_67.setTristate(True)
        self.checkBox_67.setObjectName("checkBox_67")
        self.buttonGroup_2.addButton(self.checkBox_67)
        self.gridLayout_2.addWidget(self.checkBox_67, 4, 5, 1, 1)
        self.checkBox_68 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_68.setText("")
        self.checkBox_68.setTristate(True)
        self.checkBox_68.setObjectName("checkBox_68")
        self.buttonGroup_2.addButton(self.checkBox_68)
        self.gridLayout_2.addWidget(self.checkBox_68, 4, 6, 1, 1)
        self.checkBox_69 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_69.setText("")
        self.checkBox_69.setTristate(True)
        self.checkBox_69.setObjectName("checkBox_69")
        self.buttonGroup_2.addButton(self.checkBox_69)
        self.gridLayout_2.addWidget(self.checkBox_69, 4, 7, 1, 1)
        self.checkBox_70 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_70.setText("")
        self.checkBox_70.setTristate(True)
        self.checkBox_70.setObjectName("checkBox_70")
        self.buttonGroup_2.addButton(self.checkBox_70)
        self.gridLayout_2.addWidget(self.checkBox_70, 4, 8, 1, 1)
        self.checkBox_71 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_71.setText("")
        self.checkBox_71.setTristate(True)
        self.checkBox_71.setObjectName("checkBox_71")
        self.buttonGroup_2.addButton(self.checkBox_71)
        self.gridLayout_2.addWidget(self.checkBox_71, 4, 9, 1, 1)
        self.checkBox_72 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_72.setText("")
        self.checkBox_72.setTristate(True)
        self.checkBox_72.setObjectName("checkBox_72")
        self.buttonGroup_2.addButton(self.checkBox_72)
        self.gridLayout_2.addWidget(self.checkBox_72, 4, 10, 1, 1)
        self.checkBox_73 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_73.setText("")
        self.checkBox_73.setTristate(True)
        self.checkBox_73.setObjectName("checkBox_73")
        self.buttonGroup_2.addButton(self.checkBox_73)
        self.gridLayout_2.addWidget(self.checkBox_73, 1, 4, 1, 1)
        self.checkBox_74 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_74.setText("")
        self.checkBox_74.setTristate(True)
        self.checkBox_74.setObjectName("checkBox_74")
        self.buttonGroup_2.addButton(self.checkBox_74)
        self.gridLayout_2.addWidget(self.checkBox_74, 1, 5, 1, 1)
        self.checkBox_75 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_75.setText("")
        self.checkBox_75.setTristate(True)
        self.checkBox_75.setObjectName("checkBox_75")
        self.buttonGroup_2.addButton(self.checkBox_75)
        self.gridLayout_2.addWidget(self.checkBox_75, 1, 6, 1, 1)
        self.checkBox_76 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_76.setText("")
        self.checkBox_76.setTristate(True)
        self.checkBox_76.setObjectName("checkBox_76")
        self.buttonGroup_2.addButton(self.checkBox_76)
        self.gridLayout_2.addWidget(self.checkBox_76, 1, 7, 1, 1)
        self.checkBox_77 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_77.setText("")
        self.checkBox_77.setTristate(True)
        self.checkBox_77.setObjectName("checkBox_77")
        self.buttonGroup_2.addButton(self.checkBox_77)
        self.gridLayout_2.addWidget(self.checkBox_77, 1, 8, 1, 1)
        self.checkBox_78 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_78.setText("")
        self.checkBox_78.setTristate(True)
        self.checkBox_78.setObjectName("checkBox_78")
        self.buttonGroup_2.addButton(self.checkBox_78)
        self.gridLayout_2.addWidget(self.checkBox_78, 1, 9, 1, 1)
        self.checkBox_79 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_79.setText("")
        self.checkBox_79.setTristate(True)
        self.checkBox_79.setObjectName("checkBox_79")
        self.buttonGroup_2.addButton(self.checkBox_79)
        self.gridLayout_2.addWidget(self.checkBox_79, 1, 10, 1, 1)
        self.checkBox_80 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_80.setText("")
        self.checkBox_80.setTristate(True)
        self.checkBox_80.setObjectName("checkBox_80")
        self.buttonGroup_2.addButton(self.checkBox_80)
        self.gridLayout_2.addWidget(self.checkBox_80, 2, 2, 1, 1)
        self.checkBox_81 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_81.setText("")
        self.checkBox_81.setTristate(True)
        self.checkBox_81.setObjectName("checkBox_81")
        self.buttonGroup_2.addButton(self.checkBox_81)
        self.gridLayout_2.addWidget(self.checkBox_81, 2, 3, 1, 1)
        self.checkBox_82 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_82.setText("")
        self.checkBox_82.setTristate(True)
        self.checkBox_82.setObjectName("checkBox_82")
        self.buttonGroup_2.addButton(self.checkBox_82)
        self.gridLayout_2.addWidget(self.checkBox_82, 2, 4, 1, 1)
        self.checkBox_83 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_83.setText("")
        self.checkBox_83.setTristate(True)
        self.checkBox_83.setObjectName("checkBox_83")
        self.buttonGroup_2.addButton(self.checkBox_83)
        self.gridLayout_2.addWidget(self.checkBox_83, 2, 5, 1, 1)
        self.checkBox_84 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_84.setText("")
        self.checkBox_84.setTristate(True)
        self.checkBox_84.setObjectName("checkBox_84")
        self.buttonGroup_2.addButton(self.checkBox_84)
        self.gridLayout_2.addWidget(self.checkBox_84, 2, 6, 1, 1)
        self.checkBox_85 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_85.setText("")
        self.checkBox_85.setTristate(True)
        self.checkBox_85.setObjectName("checkBox_85")
        self.buttonGroup_2.addButton(self.checkBox_85)
        self.gridLayout_2.addWidget(self.checkBox_85, 2, 7, 1, 1)
        self.checkBox_86 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_86.setText("")
        self.checkBox_86.setTristate(True)
        self.checkBox_86.setObjectName("checkBox_86")
        self.buttonGroup_2.addButton(self.checkBox_86)
        self.gridLayout_2.addWidget(self.checkBox_86, 2, 8, 1, 1)
        self.checkBox_87 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_87.setText("")
        self.checkBox_87.setTristate(True)
        self.checkBox_87.setObjectName("checkBox_87")
        self.buttonGroup_2.addButton(self.checkBox_87)
        self.gridLayout_2.addWidget(self.checkBox_87, 2, 9, 1, 1)
        self.checkBox_88 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_88.setText("")
        self.checkBox_88.setTristate(True)
        self.checkBox_88.setObjectName("checkBox_88")
        self.buttonGroup_2.addButton(self.checkBox_88)
        self.gridLayout_2.addWidget(self.checkBox_88, 2, 10, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setText("")
        self.checkBox_2.setTristate(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup_2.addButton(self.checkBox_2)
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox_89 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_89.setText("")
        self.checkBox_89.setTristate(True)
        self.checkBox_89.setObjectName("checkBox_89")
        self.buttonGroup_2.addButton(self.checkBox_89)
        self.gridLayout_2.addWidget(self.checkBox_89, 8, 1, 1, 1)
        self.checkBox_90 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_90.setText("")
        self.checkBox_90.setTristate(True)
        self.checkBox_90.setObjectName("checkBox_90")
        self.buttonGroup_2.addButton(self.checkBox_90)
        self.gridLayout_2.addWidget(self.checkBox_90, 9, 1, 1, 1)
        self.checkBox_91 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_91.setText("")
        self.checkBox_91.setTristate(True)
        self.checkBox_91.setObjectName("checkBox_91")
        self.buttonGroup_2.addButton(self.checkBox_91)
        self.gridLayout_2.addWidget(self.checkBox_91, 10, 1, 1, 1)
        self.checkBox_92 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_92.setText("")
        self.checkBox_92.setTristate(True)
        self.checkBox_92.setObjectName("checkBox_92")
        self.buttonGroup_2.addButton(self.checkBox_92)
        self.gridLayout_2.addWidget(self.checkBox_92, 1, 2, 1, 1)
        self.checkBox_148 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_148.setText("")
        self.checkBox_148.setTristate(True)
        self.checkBox_148.setObjectName("checkBox_148")
        self.buttonGroup_2.addButton(self.checkBox_148)
        self.gridLayout_2.addWidget(self.checkBox_148, 5, 2, 1, 1)
        self.checkBox_149 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_149.setText("")
        self.checkBox_149.setTristate(True)
        self.checkBox_149.setObjectName("checkBox_149")
        self.buttonGroup_2.addButton(self.checkBox_149)
        self.gridLayout_2.addWidget(self.checkBox_149, 5, 3, 1, 1)
        self.checkBox_150 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_150.setText("")
        self.checkBox_150.setTristate(True)
        self.checkBox_150.setObjectName("checkBox_150")
        self.buttonGroup_2.addButton(self.checkBox_150)
        self.gridLayout_2.addWidget(self.checkBox_150, 5, 4, 1, 1)
        self.checkBox_151 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_151.setText("")
        self.checkBox_151.setTristate(True)
        self.checkBox_151.setObjectName("checkBox_151")
        self.buttonGroup_2.addButton(self.checkBox_151)
        self.gridLayout_2.addWidget(self.checkBox_151, 5, 5, 1, 1)
        self.checkBox_152 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_152.setText("")
        self.checkBox_152.setTristate(True)
        self.checkBox_152.setObjectName("checkBox_152")
        self.buttonGroup_2.addButton(self.checkBox_152)
        self.gridLayout_2.addWidget(self.checkBox_152, 5, 6, 1, 1)
        self.checkBox_153 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_153.setText("")
        self.checkBox_153.setTristate(True)
        self.checkBox_153.setObjectName("checkBox_153")
        self.buttonGroup_2.addButton(self.checkBox_153)
        self.gridLayout_2.addWidget(self.checkBox_153, 5, 7, 1, 1)
        self.checkBox_154 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_154.setText("")
        self.checkBox_154.setTristate(True)
        self.checkBox_154.setObjectName("checkBox_154")
        self.buttonGroup_2.addButton(self.checkBox_154)
        self.gridLayout_2.addWidget(self.checkBox_154, 5, 8, 1, 1)
        self.checkBox_155 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_155.setText("")
        self.checkBox_155.setTristate(True)
        self.checkBox_155.setObjectName("checkBox_155")
        self.buttonGroup_2.addButton(self.checkBox_155)
        self.gridLayout_2.addWidget(self.checkBox_155, 5, 9, 1, 1)
        self.checkBox_156 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_156.setText("")
        self.checkBox_156.setTristate(True)
        self.checkBox_156.setObjectName("checkBox_156")
        self.buttonGroup_2.addButton(self.checkBox_156)
        self.gridLayout_2.addWidget(self.checkBox_156, 5, 10, 1, 1)
        self.checkBox_157 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_157.setText("")
        self.checkBox_157.setTristate(True)
        self.checkBox_157.setObjectName("checkBox_157")
        self.buttonGroup_2.addButton(self.checkBox_157)
        self.gridLayout_2.addWidget(self.checkBox_157, 6, 2, 1, 1)
        self.checkBox_158 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_158.setText("")
        self.checkBox_158.setTristate(True)
        self.checkBox_158.setObjectName("checkBox_158")
        self.buttonGroup_2.addButton(self.checkBox_158)
        self.gridLayout_2.addWidget(self.checkBox_158, 6, 3, 1, 1)
        self.checkBox_159 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_159.setText("")
        self.checkBox_159.setTristate(True)
        self.checkBox_159.setObjectName("checkBox_159")
        self.buttonGroup_2.addButton(self.checkBox_159)
        self.gridLayout_2.addWidget(self.checkBox_159, 6, 4, 1, 1)
        self.checkBox_160 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_160.setText("")
        self.checkBox_160.setTristate(True)
        self.checkBox_160.setObjectName("checkBox_160")
        self.buttonGroup_2.addButton(self.checkBox_160)
        self.gridLayout_2.addWidget(self.checkBox_160, 6, 5, 1, 1)
        self.checkBox_161 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_161.setText("")
        self.checkBox_161.setTristate(True)
        self.checkBox_161.setObjectName("checkBox_161")
        self.buttonGroup_2.addButton(self.checkBox_161)
        self.gridLayout_2.addWidget(self.checkBox_161, 6, 6, 1, 1)
        self.checkBox_162 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_162.setText("")
        self.checkBox_162.setTristate(True)
        self.checkBox_162.setObjectName("checkBox_162")
        self.buttonGroup_2.addButton(self.checkBox_162)
        self.gridLayout_2.addWidget(self.checkBox_162, 6, 7, 1, 1)
        self.checkBox_163 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_163.setText("")
        self.checkBox_163.setTristate(True)
        self.checkBox_163.setObjectName("checkBox_163")
        self.buttonGroup_2.addButton(self.checkBox_163)
        self.gridLayout_2.addWidget(self.checkBox_163, 6, 8, 1, 1)
        self.checkBox_164 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_164.setText("")
        self.checkBox_164.setTristate(True)
        self.checkBox_164.setObjectName("checkBox_164")
        self.buttonGroup_2.addButton(self.checkBox_164)
        self.gridLayout_2.addWidget(self.checkBox_164, 6, 9, 1, 1)
        self.checkBox_165 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_165.setText("")
        self.checkBox_165.setTristate(True)
        self.checkBox_165.setObjectName("checkBox_165")
        self.buttonGroup_2.addButton(self.checkBox_165)
        self.gridLayout_2.addWidget(self.checkBox_165, 6, 10, 1, 1)
        self.checkBox_166 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_166.setText("")
        self.checkBox_166.setTristate(True)
        self.checkBox_166.setObjectName("checkBox_166")
        self.buttonGroup_2.addButton(self.checkBox_166)
        self.gridLayout_2.addWidget(self.checkBox_166, 7, 2, 1, 1)
        self.checkBox_167 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_167.setText("")
        self.checkBox_167.setTristate(True)
        self.checkBox_167.setObjectName("checkBox_167")
        self.buttonGroup_2.addButton(self.checkBox_167)
        self.gridLayout_2.addWidget(self.checkBox_167, 7, 3, 1, 1)
        self.checkBox_168 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_168.setText("")
        self.checkBox_168.setTristate(True)
        self.checkBox_168.setObjectName("checkBox_168")
        self.buttonGroup_2.addButton(self.checkBox_168)
        self.gridLayout_2.addWidget(self.checkBox_168, 7, 4, 1, 1)
        self.checkBox_169 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_169.setText("")
        self.checkBox_169.setTristate(True)
        self.checkBox_169.setObjectName("checkBox_169")
        self.buttonGroup_2.addButton(self.checkBox_169)
        self.gridLayout_2.addWidget(self.checkBox_169, 7, 5, 1, 1)
        self.checkBox_170 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_170.setText("")
        self.checkBox_170.setTristate(True)
        self.checkBox_170.setObjectName("checkBox_170")
        self.buttonGroup_2.addButton(self.checkBox_170)
        self.gridLayout_2.addWidget(self.checkBox_170, 7, 6, 1, 1)
        self.checkBox_171 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_171.setText("")
        self.checkBox_171.setTristate(True)
        self.checkBox_171.setObjectName("checkBox_171")
        self.buttonGroup_2.addButton(self.checkBox_171)
        self.gridLayout_2.addWidget(self.checkBox_171, 7, 7, 1, 1)
        self.checkBox_172 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_172.setText("")
        self.checkBox_172.setTristate(True)
        self.checkBox_172.setObjectName("checkBox_172")
        self.buttonGroup_2.addButton(self.checkBox_172)
        self.gridLayout_2.addWidget(self.checkBox_172, 7, 8, 1, 1)
        self.checkBox_173 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_173.setText("")
        self.checkBox_173.setTristate(True)
        self.checkBox_173.setObjectName("checkBox_173")
        self.buttonGroup_2.addButton(self.checkBox_173)
        self.gridLayout_2.addWidget(self.checkBox_173, 7, 9, 1, 1)
        self.checkBox_174 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_174.setText("")
        self.checkBox_174.setTristate(True)
        self.checkBox_174.setObjectName("checkBox_174")
        self.buttonGroup_2.addButton(self.checkBox_174)
        self.gridLayout_2.addWidget(self.checkBox_174, 7, 10, 1, 1)
        self.checkBox_175 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_175.setText("")
        self.checkBox_175.setTristate(True)
        self.checkBox_175.setObjectName("checkBox_175")
        self.buttonGroup_2.addButton(self.checkBox_175)
        self.gridLayout_2.addWidget(self.checkBox_175, 8, 2, 1, 1)
        self.checkBox_176 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_176.setText("")
        self.checkBox_176.setTristate(True)
        self.checkBox_176.setObjectName("checkBox_176")
        self.buttonGroup_2.addButton(self.checkBox_176)
        self.gridLayout_2.addWidget(self.checkBox_176, 8, 3, 1, 1)
        self.checkBox_177 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_177.setText("")
        self.checkBox_177.setTristate(True)
        self.checkBox_177.setObjectName("checkBox_177")
        self.buttonGroup_2.addButton(self.checkBox_177)
        self.gridLayout_2.addWidget(self.checkBox_177, 8, 4, 1, 1)
        self.checkBox_178 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_178.setText("")
        self.checkBox_178.setTristate(True)
        self.checkBox_178.setObjectName("checkBox_178")
        self.buttonGroup_2.addButton(self.checkBox_178)
        self.gridLayout_2.addWidget(self.checkBox_178, 8, 5, 1, 1)
        self.checkBox_179 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_179.setText("")
        self.checkBox_179.setTristate(True)
        self.checkBox_179.setObjectName("checkBox_179")
        self.buttonGroup_2.addButton(self.checkBox_179)
        self.gridLayout_2.addWidget(self.checkBox_179, 8, 6, 1, 1)
        self.checkBox_180 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_180.setText("")
        self.checkBox_180.setTristate(True)
        self.checkBox_180.setObjectName("checkBox_180")
        self.buttonGroup_2.addButton(self.checkBox_180)
        self.gridLayout_2.addWidget(self.checkBox_180, 8, 7, 1, 1)
        self.checkBox_181 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_181.setText("")
        self.checkBox_181.setTristate(True)
        self.checkBox_181.setObjectName("checkBox_181")
        self.buttonGroup_2.addButton(self.checkBox_181)
        self.gridLayout_2.addWidget(self.checkBox_181, 8, 8, 1, 1)
        self.checkBox_182 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_182.setText("")
        self.checkBox_182.setTristate(True)
        self.checkBox_182.setObjectName("checkBox_182")
        self.buttonGroup_2.addButton(self.checkBox_182)
        self.gridLayout_2.addWidget(self.checkBox_182, 8, 9, 1, 1)
        self.checkBox_183 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_183.setText("")
        self.checkBox_183.setTristate(True)
        self.checkBox_183.setObjectName("checkBox_183")
        self.buttonGroup_2.addButton(self.checkBox_183)
        self.gridLayout_2.addWidget(self.checkBox_183, 8, 10, 1, 1)
        self.checkBox_184 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_184.setText("")
        self.checkBox_184.setTristate(True)
        self.checkBox_184.setObjectName("checkBox_184")
        self.buttonGroup_2.addButton(self.checkBox_184)
        self.gridLayout_2.addWidget(self.checkBox_184, 9, 2, 1, 1)
        self.checkBox_185 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_185.setText("")
        self.checkBox_185.setTristate(True)
        self.checkBox_185.setObjectName("checkBox_185")
        self.buttonGroup_2.addButton(self.checkBox_185)
        self.gridLayout_2.addWidget(self.checkBox_185, 9, 3, 1, 1)
        self.checkBox_186 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_186.setText("")
        self.checkBox_186.setTristate(True)
        self.checkBox_186.setObjectName("checkBox_186")
        self.buttonGroup_2.addButton(self.checkBox_186)
        self.gridLayout_2.addWidget(self.checkBox_186, 9, 4, 1, 1)
        self.checkBox_187 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_187.setText("")
        self.checkBox_187.setTristate(True)
        self.checkBox_187.setObjectName("checkBox_187")
        self.buttonGroup_2.addButton(self.checkBox_187)
        self.gridLayout_2.addWidget(self.checkBox_187, 9, 5, 1, 1)
        self.checkBox_188 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_188.setText("")
        self.checkBox_188.setTristate(True)
        self.checkBox_188.setObjectName("checkBox_188")
        self.buttonGroup_2.addButton(self.checkBox_188)
        self.gridLayout_2.addWidget(self.checkBox_188, 9, 6, 1, 1)
        self.checkBox_189 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_189.setText("")
        self.checkBox_189.setTristate(True)
        self.checkBox_189.setObjectName("checkBox_189")
        self.buttonGroup_2.addButton(self.checkBox_189)
        self.gridLayout_2.addWidget(self.checkBox_189, 9, 7, 1, 1)
        self.checkBox_190 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_190.setText("")
        self.checkBox_190.setTristate(True)
        self.checkBox_190.setObjectName("checkBox_190")
        self.buttonGroup_2.addButton(self.checkBox_190)
        self.gridLayout_2.addWidget(self.checkBox_190, 9, 8, 1, 1)
        self.checkBox_191 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_191.setText("")
        self.checkBox_191.setTristate(True)
        self.checkBox_191.setObjectName("checkBox_191")
        self.buttonGroup_2.addButton(self.checkBox_191)
        self.gridLayout_2.addWidget(self.checkBox_191, 9, 9, 1, 1)
        self.checkBox_192 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_192.setText("")
        self.checkBox_192.setTristate(True)
        self.checkBox_192.setObjectName("checkBox_192")
        self.buttonGroup_2.addButton(self.checkBox_192)
        self.gridLayout_2.addWidget(self.checkBox_192, 9, 10, 1, 1)
        self.checkBox_193 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_193.setText("")
        self.checkBox_193.setTristate(True)
        self.checkBox_193.setObjectName("checkBox_193")
        self.buttonGroup_2.addButton(self.checkBox_193)
        self.gridLayout_2.addWidget(self.checkBox_193, 10, 2, 1, 1)
        self.checkBox_194 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_194.setText("")
        self.checkBox_194.setTristate(True)
        self.checkBox_194.setObjectName("checkBox_194")
        self.buttonGroup_2.addButton(self.checkBox_194)
        self.gridLayout_2.addWidget(self.checkBox_194, 10, 3, 1, 1)
        self.checkBox_195 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_195.setText("")
        self.checkBox_195.setTristate(True)
        self.checkBox_195.setObjectName("checkBox_195")
        self.buttonGroup_2.addButton(self.checkBox_195)
        self.gridLayout_2.addWidget(self.checkBox_195, 10, 4, 1, 1)
        self.checkBox_196 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_196.setText("")
        self.checkBox_196.setTristate(True)
        self.checkBox_196.setObjectName("checkBox_196")
        self.buttonGroup_2.addButton(self.checkBox_196)
        self.gridLayout_2.addWidget(self.checkBox_196, 10, 5, 1, 1)
        self.checkBox_197 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_197.setText("")
        self.checkBox_197.setTristate(True)
        self.checkBox_197.setObjectName("checkBox_197")
        self.buttonGroup_2.addButton(self.checkBox_197)
        self.gridLayout_2.addWidget(self.checkBox_197, 10, 6, 1, 1)
        self.checkBox_198 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_198.setText("")
        self.checkBox_198.setTristate(True)
        self.checkBox_198.setObjectName("checkBox_198")
        self.buttonGroup_2.addButton(self.checkBox_198)
        self.gridLayout_2.addWidget(self.checkBox_198, 10, 7, 1, 1)
        self.checkBox_199 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_199.setText("")
        self.checkBox_199.setTristate(True)
        self.checkBox_199.setObjectName("checkBox_199")
        self.buttonGroup_2.addButton(self.checkBox_199)
        self.gridLayout_2.addWidget(self.checkBox_199, 10, 8, 1, 1)
        self.checkBox_200 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_200.setText("")
        self.checkBox_200.setTristate(True)
        self.checkBox_200.setObjectName("checkBox_200")
        self.buttonGroup_2.addButton(self.checkBox_200)
        self.gridLayout_2.addWidget(self.checkBox_200, 10, 9, 1, 1)
        self.checkBox_201 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_201.setText("")
        self.checkBox_201.setTristate(True)
        self.checkBox_201.setObjectName("checkBox_201")
        self.buttonGroup_2.addButton(self.checkBox_201)
        self.gridLayout_2.addWidget(self.checkBox_201, 10, 10, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 5, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 0, 6, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 0, 7, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 8, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 9, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 0, 10, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 6, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 7, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 8, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 9, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 10, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 21))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuGame.addAction(self.actionStart)
        self.menuGame.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BattleShip"))
        self.Player1_name.setText(_translate("MainWindow", "Player 1"))
        self.label_5.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "8"))
        self.label_10.setText(_translate("MainWindow", "7"))
        self.label_8.setText(_translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "3"))
        self.label_7.setText(_translate("MainWindow", "4"))
        self.label_9.setText(_translate("MainWindow", "6"))
        self.label_12.setText(_translate("MainWindow", "9"))
        self.label_13.setText(_translate("MainWindow", "10"))
        self.label_14.setText(_translate("MainWindow", "A"))
        self.label_15.setText(_translate("MainWindow", "B"))
        self.label_16.setText(_translate("MainWindow", "C"))
        self.label_17.setText(_translate("MainWindow", "D"))
        self.label_18.setText(_translate("MainWindow", "E"))
        self.label_19.setText(_translate("MainWindow", "F"))
        self.label_20.setText(_translate("MainWindow", "G"))
        self.label_21.setText(_translate("MainWindow", "H"))
        self.label_22.setText(_translate("MainWindow", "I"))
        self.label_23.setText(_translate("MainWindow", "J"))
        self.Player2_name.setText(_translate("MainWindow", "Player 2"))
        self.label_25.setText(_translate("MainWindow", "1"))
        self.label_24.setText(_translate("MainWindow", "A"))
        self.label_26.setText(_translate("MainWindow", "2"))
        self.label_27.setText(_translate("MainWindow", "3"))
        self.label_28.setText(_translate("MainWindow", "4"))
        self.label_29.setText(_translate("MainWindow", "5"))
        self.label_30.setText(_translate("MainWindow", "6"))
        self.label_31.setText(_translate("MainWindow", "7"))
        self.label_32.setText(_translate("MainWindow", "8"))
        self.label_33.setText(_translate("MainWindow", "9"))
        self.label_34.setText(_translate("MainWindow", "10"))
        self.label_35.setText(_translate("MainWindow", "B"))
        self.label_36.setText(_translate("MainWindow", "C"))
        self.label_37.setText(_translate("MainWindow", "D"))
        self.label_38.setText(_translate("MainWindow", "E"))
        self.label_39.setText(_translate("MainWindow", "F"))
        self.label_40.setText(_translate("MainWindow", "G"))
        self.label_41.setText(_translate("MainWindow", "H"))
        self.label_42.setText(_translate("MainWindow", "I"))
        self.label_43.setText(_translate("MainWindow", "J"))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setStatusTip(_translate("MainWindow", "Start the game"))
        self.actionStart.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the game"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))
        self.actionAbout_us.setStatusTip(_translate("MainWindow", "Developer\'s contact information"))
        self.actionAbout_us.setShortcut(_translate("MainWindow", "Ctrl+H"))

