# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 360)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color : #5500FF;")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_8.addWidget(self.textBrowser)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Player1_name = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Player1_name.setFont(font)
        self.Player1_name.setObjectName("Player1_name")
        self.verticalLayout_3.addWidget(self.Player1_name)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setText("")
        self.checkBox_6.setTristate(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 5, 1, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(Form)
        self.checkBox_13.setText("")
        self.checkBox_13.setTristate(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout.addWidget(self.checkBox_13, 1, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setText("")
        self.checkBox_5.setTristate(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 4, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setText("")
        self.checkBox_7.setTristate(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 6, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setText("")
        self.checkBox_8.setTristate(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 7, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setText("")
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setText("")
        self.checkBox_4.setTristate(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 3, 1, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(Form)
        self.checkBox_30.setText("")
        self.checkBox_30.setTristate(True)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout.addWidget(self.checkBox_30, 3, 2, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(Form)
        self.checkBox_31.setText("")
        self.checkBox_31.setTristate(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout.addWidget(self.checkBox_31, 3, 3, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(Form)
        self.checkBox_32.setText("")
        self.checkBox_32.setTristate(True)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout.addWidget(self.checkBox_32, 3, 4, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(Form)
        self.checkBox_33.setText("")
        self.checkBox_33.setTristate(True)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout.addWidget(self.checkBox_33, 3, 5, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(Form)
        self.checkBox_34.setText("")
        self.checkBox_34.setTristate(True)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout.addWidget(self.checkBox_34, 3, 6, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(Form)
        self.checkBox_35.setText("")
        self.checkBox_35.setTristate(True)
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout.addWidget(self.checkBox_35, 3, 7, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(Form)
        self.checkBox_36.setText("")
        self.checkBox_36.setTristate(True)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout.addWidget(self.checkBox_36, 3, 8, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(Form)
        self.checkBox_37.setText("")
        self.checkBox_37.setTristate(True)
        self.checkBox_37.setObjectName("checkBox_37")
        self.gridLayout.addWidget(self.checkBox_37, 3, 9, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(Form)
        self.checkBox_38.setText("")
        self.checkBox_38.setTristate(True)
        self.checkBox_38.setObjectName("checkBox_38")
        self.gridLayout.addWidget(self.checkBox_38, 3, 10, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(Form)
        self.checkBox_39.setText("")
        self.checkBox_39.setTristate(True)
        self.checkBox_39.setObjectName("checkBox_39")
        self.gridLayout.addWidget(self.checkBox_39, 4, 2, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(Form)
        self.checkBox_40.setText("")
        self.checkBox_40.setTristate(True)
        self.checkBox_40.setObjectName("checkBox_40")
        self.gridLayout.addWidget(self.checkBox_40, 4, 3, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(Form)
        self.checkBox_41.setText("")
        self.checkBox_41.setTristate(True)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout.addWidget(self.checkBox_41, 4, 4, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(Form)
        self.checkBox_42.setText("")
        self.checkBox_42.setTristate(True)
        self.checkBox_42.setObjectName("checkBox_42")
        self.gridLayout.addWidget(self.checkBox_42, 4, 5, 1, 1)
        self.checkBox_43 = QtWidgets.QCheckBox(Form)
        self.checkBox_43.setText("")
        self.checkBox_43.setTristate(True)
        self.checkBox_43.setObjectName("checkBox_43")
        self.gridLayout.addWidget(self.checkBox_43, 4, 6, 1, 1)
        self.checkBox_44 = QtWidgets.QCheckBox(Form)
        self.checkBox_44.setText("")
        self.checkBox_44.setTristate(True)
        self.checkBox_44.setObjectName("checkBox_44")
        self.gridLayout.addWidget(self.checkBox_44, 4, 7, 1, 1)
        self.checkBox_45 = QtWidgets.QCheckBox(Form)
        self.checkBox_45.setText("")
        self.checkBox_45.setTristate(True)
        self.checkBox_45.setObjectName("checkBox_45")
        self.gridLayout.addWidget(self.checkBox_45, 4, 8, 1, 1)
        self.checkBox_46 = QtWidgets.QCheckBox(Form)
        self.checkBox_46.setText("")
        self.checkBox_46.setTristate(True)
        self.checkBox_46.setObjectName("checkBox_46")
        self.gridLayout.addWidget(self.checkBox_46, 4, 9, 1, 1)
        self.checkBox_47 = QtWidgets.QCheckBox(Form)
        self.checkBox_47.setText("")
        self.checkBox_47.setTristate(True)
        self.checkBox_47.setObjectName("checkBox_47")
        self.gridLayout.addWidget(self.checkBox_47, 4, 10, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(Form)
        self.checkBox_14.setText("")
        self.checkBox_14.setTristate(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout.addWidget(self.checkBox_14, 1, 4, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(Form)
        self.checkBox_15.setText("")
        self.checkBox_15.setTristate(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout.addWidget(self.checkBox_15, 1, 5, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(Form)
        self.checkBox_16.setText("")
        self.checkBox_16.setTristate(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout.addWidget(self.checkBox_16, 1, 6, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(Form)
        self.checkBox_17.setText("")
        self.checkBox_17.setTristate(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout.addWidget(self.checkBox_17, 1, 7, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(Form)
        self.checkBox_18.setText("")
        self.checkBox_18.setTristate(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout.addWidget(self.checkBox_18, 1, 8, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(Form)
        self.checkBox_19.setText("")
        self.checkBox_19.setTristate(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout.addWidget(self.checkBox_19, 1, 9, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(Form)
        self.checkBox_20.setText("")
        self.checkBox_20.setTristate(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 1, 10, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(Form)
        self.checkBox_21.setText("")
        self.checkBox_21.setTristate(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 2, 2, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(Form)
        self.checkBox_22.setText("")
        self.checkBox_22.setTristate(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout.addWidget(self.checkBox_22, 2, 3, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(Form)
        self.checkBox_23.setText("")
        self.checkBox_23.setTristate(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout.addWidget(self.checkBox_23, 2, 4, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(Form)
        self.checkBox_24.setText("")
        self.checkBox_24.setTristate(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout.addWidget(self.checkBox_24, 2, 5, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(Form)
        self.checkBox_25.setText("")
        self.checkBox_25.setTristate(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout.addWidget(self.checkBox_25, 2, 6, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(Form)
        self.checkBox_26.setText("")
        self.checkBox_26.setTristate(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout.addWidget(self.checkBox_26, 2, 7, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(Form)
        self.checkBox_27.setText("")
        self.checkBox_27.setTristate(True)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout.addWidget(self.checkBox_27, 2, 8, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(Form)
        self.checkBox_28.setText("")
        self.checkBox_28.setTristate(True)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout.addWidget(self.checkBox_28, 2, 9, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(Form)
        self.checkBox_29.setText("")
        self.checkBox_29.setTristate(True)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout.addWidget(self.checkBox_29, 2, 10, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(16, 16))
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setText("")
        self.checkBox_9.setTristate(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 8, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setText("")
        self.checkBox_10.setTristate(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 9, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setText("")
        self.checkBox_11.setTristate(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout.addWidget(self.checkBox_11, 10, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setText("")
        self.checkBox_12.setTristate(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout.addWidget(self.checkBox_12, 1, 2, 1, 1)
        self.checkBox_94 = QtWidgets.QCheckBox(Form)
        self.checkBox_94.setText("")
        self.checkBox_94.setTristate(True)
        self.checkBox_94.setObjectName("checkBox_94")
        self.gridLayout.addWidget(self.checkBox_94, 5, 2, 1, 1)
        self.checkBox_95 = QtWidgets.QCheckBox(Form)
        self.checkBox_95.setText("")
        self.checkBox_95.setTristate(True)
        self.checkBox_95.setObjectName("checkBox_95")
        self.gridLayout.addWidget(self.checkBox_95, 5, 3, 1, 1)
        self.checkBox_96 = QtWidgets.QCheckBox(Form)
        self.checkBox_96.setText("")
        self.checkBox_96.setTristate(True)
        self.checkBox_96.setObjectName("checkBox_96")
        self.gridLayout.addWidget(self.checkBox_96, 5, 4, 1, 1)
        self.checkBox_97 = QtWidgets.QCheckBox(Form)
        self.checkBox_97.setText("")
        self.checkBox_97.setTristate(True)
        self.checkBox_97.setObjectName("checkBox_97")
        self.gridLayout.addWidget(self.checkBox_97, 5, 5, 1, 1)
        self.checkBox_98 = QtWidgets.QCheckBox(Form)
        self.checkBox_98.setText("")
        self.checkBox_98.setTristate(True)
        self.checkBox_98.setObjectName("checkBox_98")
        self.gridLayout.addWidget(self.checkBox_98, 5, 6, 1, 1)
        self.checkBox_99 = QtWidgets.QCheckBox(Form)
        self.checkBox_99.setText("")
        self.checkBox_99.setTristate(True)
        self.checkBox_99.setObjectName("checkBox_99")
        self.gridLayout.addWidget(self.checkBox_99, 5, 7, 1, 1)
        self.checkBox_100 = QtWidgets.QCheckBox(Form)
        self.checkBox_100.setText("")
        self.checkBox_100.setTristate(True)
        self.checkBox_100.setObjectName("checkBox_100")
        self.gridLayout.addWidget(self.checkBox_100, 5, 8, 1, 1)
        self.checkBox_101 = QtWidgets.QCheckBox(Form)
        self.checkBox_101.setText("")
        self.checkBox_101.setTristate(True)
        self.checkBox_101.setObjectName("checkBox_101")
        self.gridLayout.addWidget(self.checkBox_101, 5, 9, 1, 1)
        self.checkBox_102 = QtWidgets.QCheckBox(Form)
        self.checkBox_102.setText("")
        self.checkBox_102.setTristate(True)
        self.checkBox_102.setObjectName("checkBox_102")
        self.gridLayout.addWidget(self.checkBox_102, 5, 10, 1, 1)
        self.checkBox_103 = QtWidgets.QCheckBox(Form)
        self.checkBox_103.setText("")
        self.checkBox_103.setTristate(True)
        self.checkBox_103.setObjectName("checkBox_103")
        self.gridLayout.addWidget(self.checkBox_103, 6, 2, 1, 1)
        self.checkBox_104 = QtWidgets.QCheckBox(Form)
        self.checkBox_104.setText("")
        self.checkBox_104.setTristate(True)
        self.checkBox_104.setObjectName("checkBox_104")
        self.gridLayout.addWidget(self.checkBox_104, 6, 3, 1, 1)
        self.checkBox_105 = QtWidgets.QCheckBox(Form)
        self.checkBox_105.setText("")
        self.checkBox_105.setTristate(True)
        self.checkBox_105.setObjectName("checkBox_105")
        self.gridLayout.addWidget(self.checkBox_105, 6, 4, 1, 1)
        self.checkBox_106 = QtWidgets.QCheckBox(Form)
        self.checkBox_106.setText("")
        self.checkBox_106.setTristate(True)
        self.checkBox_106.setObjectName("checkBox_106")
        self.gridLayout.addWidget(self.checkBox_106, 6, 5, 1, 1)
        self.checkBox_107 = QtWidgets.QCheckBox(Form)
        self.checkBox_107.setText("")
        self.checkBox_107.setTristate(True)
        self.checkBox_107.setObjectName("checkBox_107")
        self.gridLayout.addWidget(self.checkBox_107, 6, 6, 1, 1)
        self.checkBox_108 = QtWidgets.QCheckBox(Form)
        self.checkBox_108.setText("")
        self.checkBox_108.setTristate(True)
        self.checkBox_108.setObjectName("checkBox_108")
        self.gridLayout.addWidget(self.checkBox_108, 6, 7, 1, 1)
        self.checkBox_109 = QtWidgets.QCheckBox(Form)
        self.checkBox_109.setText("")
        self.checkBox_109.setTristate(True)
        self.checkBox_109.setObjectName("checkBox_109")
        self.gridLayout.addWidget(self.checkBox_109, 6, 8, 1, 1)
        self.checkBox_110 = QtWidgets.QCheckBox(Form)
        self.checkBox_110.setText("")
        self.checkBox_110.setTristate(True)
        self.checkBox_110.setObjectName("checkBox_110")
        self.gridLayout.addWidget(self.checkBox_110, 6, 9, 1, 1)
        self.checkBox_111 = QtWidgets.QCheckBox(Form)
        self.checkBox_111.setText("")
        self.checkBox_111.setTristate(True)
        self.checkBox_111.setObjectName("checkBox_111")
        self.gridLayout.addWidget(self.checkBox_111, 6, 10, 1, 1)
        self.checkBox_112 = QtWidgets.QCheckBox(Form)
        self.checkBox_112.setText("")
        self.checkBox_112.setTristate(True)
        self.checkBox_112.setObjectName("checkBox_112")
        self.gridLayout.addWidget(self.checkBox_112, 7, 2, 1, 1)
        self.checkBox_113 = QtWidgets.QCheckBox(Form)
        self.checkBox_113.setText("")
        self.checkBox_113.setTristate(True)
        self.checkBox_113.setObjectName("checkBox_113")
        self.gridLayout.addWidget(self.checkBox_113, 7, 3, 1, 1)
        self.checkBox_114 = QtWidgets.QCheckBox(Form)
        self.checkBox_114.setText("")
        self.checkBox_114.setTristate(True)
        self.checkBox_114.setObjectName("checkBox_114")
        self.gridLayout.addWidget(self.checkBox_114, 7, 4, 1, 1)
        self.checkBox_115 = QtWidgets.QCheckBox(Form)
        self.checkBox_115.setText("")
        self.checkBox_115.setTristate(True)
        self.checkBox_115.setObjectName("checkBox_115")
        self.gridLayout.addWidget(self.checkBox_115, 7, 5, 1, 1)
        self.checkBox_116 = QtWidgets.QCheckBox(Form)
        self.checkBox_116.setText("")
        self.checkBox_116.setTristate(True)
        self.checkBox_116.setObjectName("checkBox_116")
        self.gridLayout.addWidget(self.checkBox_116, 7, 6, 1, 1)
        self.checkBox_117 = QtWidgets.QCheckBox(Form)
        self.checkBox_117.setText("")
        self.checkBox_117.setTristate(True)
        self.checkBox_117.setObjectName("checkBox_117")
        self.gridLayout.addWidget(self.checkBox_117, 7, 7, 1, 1)
        self.checkBox_118 = QtWidgets.QCheckBox(Form)
        self.checkBox_118.setText("")
        self.checkBox_118.setTristate(True)
        self.checkBox_118.setObjectName("checkBox_118")
        self.gridLayout.addWidget(self.checkBox_118, 7, 8, 1, 1)
        self.checkBox_119 = QtWidgets.QCheckBox(Form)
        self.checkBox_119.setText("")
        self.checkBox_119.setTristate(True)
        self.checkBox_119.setObjectName("checkBox_119")
        self.gridLayout.addWidget(self.checkBox_119, 7, 9, 1, 1)
        self.checkBox_120 = QtWidgets.QCheckBox(Form)
        self.checkBox_120.setText("")
        self.checkBox_120.setTristate(True)
        self.checkBox_120.setObjectName("checkBox_120")
        self.gridLayout.addWidget(self.checkBox_120, 7, 10, 1, 1)
        self.checkBox_121 = QtWidgets.QCheckBox(Form)
        self.checkBox_121.setText("")
        self.checkBox_121.setTristate(True)
        self.checkBox_121.setObjectName("checkBox_121")
        self.gridLayout.addWidget(self.checkBox_121, 8, 2, 1, 1)
        self.checkBox_122 = QtWidgets.QCheckBox(Form)
        self.checkBox_122.setText("")
        self.checkBox_122.setTristate(True)
        self.checkBox_122.setObjectName("checkBox_122")
        self.gridLayout.addWidget(self.checkBox_122, 8, 3, 1, 1)
        self.checkBox_123 = QtWidgets.QCheckBox(Form)
        self.checkBox_123.setText("")
        self.checkBox_123.setTristate(True)
        self.checkBox_123.setObjectName("checkBox_123")
        self.gridLayout.addWidget(self.checkBox_123, 8, 4, 1, 1)
        self.checkBox_124 = QtWidgets.QCheckBox(Form)
        self.checkBox_124.setText("")
        self.checkBox_124.setTristate(True)
        self.checkBox_124.setObjectName("checkBox_124")
        self.gridLayout.addWidget(self.checkBox_124, 8, 5, 1, 1)
        self.checkBox_125 = QtWidgets.QCheckBox(Form)
        self.checkBox_125.setText("")
        self.checkBox_125.setTristate(True)
        self.checkBox_125.setObjectName("checkBox_125")
        self.gridLayout.addWidget(self.checkBox_125, 8, 6, 1, 1)
        self.checkBox_126 = QtWidgets.QCheckBox(Form)
        self.checkBox_126.setText("")
        self.checkBox_126.setTristate(True)
        self.checkBox_126.setObjectName("checkBox_126")
        self.gridLayout.addWidget(self.checkBox_126, 8, 7, 1, 1)
        self.checkBox_127 = QtWidgets.QCheckBox(Form)
        self.checkBox_127.setText("")
        self.checkBox_127.setTristate(True)
        self.checkBox_127.setObjectName("checkBox_127")
        self.gridLayout.addWidget(self.checkBox_127, 8, 8, 1, 1)
        self.checkBox_128 = QtWidgets.QCheckBox(Form)
        self.checkBox_128.setText("")
        self.checkBox_128.setTristate(True)
        self.checkBox_128.setObjectName("checkBox_128")
        self.gridLayout.addWidget(self.checkBox_128, 8, 9, 1, 1)
        self.checkBox_129 = QtWidgets.QCheckBox(Form)
        self.checkBox_129.setText("")
        self.checkBox_129.setTristate(True)
        self.checkBox_129.setObjectName("checkBox_129")
        self.gridLayout.addWidget(self.checkBox_129, 8, 10, 1, 1)
        self.checkBox_130 = QtWidgets.QCheckBox(Form)
        self.checkBox_130.setText("")
        self.checkBox_130.setTristate(True)
        self.checkBox_130.setObjectName("checkBox_130")
        self.gridLayout.addWidget(self.checkBox_130, 9, 2, 1, 1)
        self.checkBox_131 = QtWidgets.QCheckBox(Form)
        self.checkBox_131.setText("")
        self.checkBox_131.setTristate(True)
        self.checkBox_131.setObjectName("checkBox_131")
        self.gridLayout.addWidget(self.checkBox_131, 9, 3, 1, 1)
        self.checkBox_132 = QtWidgets.QCheckBox(Form)
        self.checkBox_132.setText("")
        self.checkBox_132.setTristate(True)
        self.checkBox_132.setObjectName("checkBox_132")
        self.gridLayout.addWidget(self.checkBox_132, 9, 4, 1, 1)
        self.checkBox_133 = QtWidgets.QCheckBox(Form)
        self.checkBox_133.setText("")
        self.checkBox_133.setTristate(True)
        self.checkBox_133.setObjectName("checkBox_133")
        self.gridLayout.addWidget(self.checkBox_133, 9, 5, 1, 1)
        self.checkBox_134 = QtWidgets.QCheckBox(Form)
        self.checkBox_134.setText("")
        self.checkBox_134.setTristate(True)
        self.checkBox_134.setObjectName("checkBox_134")
        self.gridLayout.addWidget(self.checkBox_134, 9, 6, 1, 1)
        self.checkBox_135 = QtWidgets.QCheckBox(Form)
        self.checkBox_135.setText("")
        self.checkBox_135.setTristate(True)
        self.checkBox_135.setObjectName("checkBox_135")
        self.gridLayout.addWidget(self.checkBox_135, 9, 7, 1, 1)
        self.checkBox_136 = QtWidgets.QCheckBox(Form)
        self.checkBox_136.setText("")
        self.checkBox_136.setTristate(True)
        self.checkBox_136.setObjectName("checkBox_136")
        self.gridLayout.addWidget(self.checkBox_136, 9, 8, 1, 1)
        self.checkBox_137 = QtWidgets.QCheckBox(Form)
        self.checkBox_137.setText("")
        self.checkBox_137.setTristate(True)
        self.checkBox_137.setObjectName("checkBox_137")
        self.gridLayout.addWidget(self.checkBox_137, 9, 9, 1, 1)
        self.checkBox_138 = QtWidgets.QCheckBox(Form)
        self.checkBox_138.setText("")
        self.checkBox_138.setTristate(True)
        self.checkBox_138.setObjectName("checkBox_138")
        self.gridLayout.addWidget(self.checkBox_138, 9, 10, 1, 1)
        self.checkBox_139 = QtWidgets.QCheckBox(Form)
        self.checkBox_139.setText("")
        self.checkBox_139.setTristate(True)
        self.checkBox_139.setObjectName("checkBox_139")
        self.gridLayout.addWidget(self.checkBox_139, 10, 2, 1, 1)
        self.checkBox_140 = QtWidgets.QCheckBox(Form)
        self.checkBox_140.setText("")
        self.checkBox_140.setTristate(True)
        self.checkBox_140.setObjectName("checkBox_140")
        self.gridLayout.addWidget(self.checkBox_140, 10, 3, 1, 1)
        self.checkBox_141 = QtWidgets.QCheckBox(Form)
        self.checkBox_141.setText("")
        self.checkBox_141.setTristate(True)
        self.checkBox_141.setObjectName("checkBox_141")
        self.gridLayout.addWidget(self.checkBox_141, 10, 4, 1, 1)
        self.checkBox_142 = QtWidgets.QCheckBox(Form)
        self.checkBox_142.setText("")
        self.checkBox_142.setTristate(True)
        self.checkBox_142.setObjectName("checkBox_142")
        self.gridLayout.addWidget(self.checkBox_142, 10, 5, 1, 1)
        self.checkBox_143 = QtWidgets.QCheckBox(Form)
        self.checkBox_143.setText("")
        self.checkBox_143.setTristate(True)
        self.checkBox_143.setObjectName("checkBox_143")
        self.gridLayout.addWidget(self.checkBox_143, 10, 6, 1, 1)
        self.checkBox_144 = QtWidgets.QCheckBox(Form)
        self.checkBox_144.setText("")
        self.checkBox_144.setTristate(True)
        self.checkBox_144.setObjectName("checkBox_144")
        self.gridLayout.addWidget(self.checkBox_144, 10, 7, 1, 1)
        self.checkBox_145 = QtWidgets.QCheckBox(Form)
        self.checkBox_145.setText("")
        self.checkBox_145.setTristate(True)
        self.checkBox_145.setObjectName("checkBox_145")
        self.gridLayout.addWidget(self.checkBox_145, 10, 8, 1, 1)
        self.checkBox_146 = QtWidgets.QCheckBox(Form)
        self.checkBox_146.setText("")
        self.checkBox_146.setTristate(True)
        self.checkBox_146.setObjectName("checkBox_146")
        self.gridLayout.addWidget(self.checkBox_146, 10, 9, 1, 1)
        self.checkBox_147 = QtWidgets.QCheckBox(Form)
        self.checkBox_147.setText("")
        self.checkBox_147.setTristate(True)
        self.checkBox_147.setObjectName("checkBox_147")
        self.gridLayout.addWidget(self.checkBox_147, 10, 10, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 9, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 10, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Player2_name = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Player2_name.setFont(font)
        self.Player2_name.setObjectName("Player2_name")
        self.verticalLayout_4.addWidget(self.Player2_name)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem7)
        self.gridLayout1 = QtWidgets.QGridLayout()
        self.gridLayout1.setSpacing(0)
        self.gridLayout1.setObjectName("gridLayout1")
        self.checkBox_61 = QtWidgets.QCheckBox(Form)
        self.checkBox_61.setText("")
        self.checkBox_61.setTristate(True)
        self.checkBox_61.setObjectName("checkBox_61")
        self.gridLayout1.addWidget(self.checkBox_61, 5, 1, 1, 1)
        self.checkBox_131 = QtWidgets.QCheckBox(Form)
        self.checkBox_131.setText("")
        self.checkBox_131.setTristate(True)
        self.checkBox_131.setObjectName("checkBox_131")
        self.gridLayout1.addWidget(self.checkBox_131, 1, 3, 1, 1)
        self.checkBox_51 = QtWidgets.QCheckBox(Form)
        self.checkBox_51.setText("")
        self.checkBox_51.setTristate(True)
        self.checkBox_51.setObjectName("checkBox_51")
        self.gridLayout1.addWidget(self.checkBox_51, 4, 1, 1, 1)
        self.checkBox_71 = QtWidgets.QCheckBox(Form)
        self.checkBox_71.setText("")
        self.checkBox_71.setTristate(True)
        self.checkBox_71.setObjectName("checkBox_71")
        self.gridLayout1.addWidget(self.checkBox_71, 6, 1, 1, 1)
        self.checkBox_81 = QtWidgets.QCheckBox(Form)
        self.checkBox_81.setText("")
        self.checkBox_81.setTristate(True)
        self.checkBox_81.setObjectName("checkBox_81")
        self.gridLayout1.addWidget(self.checkBox_81, 7, 1, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(Form)
        self.checkBox_31.setText("")
        self.checkBox_31.setTristate(True)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout1.addWidget(self.checkBox_31, 2, 1, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(Form)
        self.checkBox_41.setText("")
        self.checkBox_41.setTristate(True)
        self.checkBox_41.setObjectName("checkBox_41")
        self.gridLayout1.addWidget(self.checkBox_41, 3, 1, 1, 1)
        self.checkBox_301 = QtWidgets.QCheckBox(Form)
        self.checkBox_301.setText("")
        self.checkBox_301.setTristate(True)
        self.checkBox_301.setObjectName("checkBox_301")
        self.gridLayout1.addWidget(self.checkBox_301, 3, 2, 1, 1)
        self.checkBox_311 = QtWidgets.QCheckBox(Form)
        self.checkBox_311.setText("")
        self.checkBox_311.setTristate(True)
        self.checkBox_311.setObjectName("checkBox_311")
        self.gridLayout1.addWidget(self.checkBox_311, 3, 3, 1, 1)
        self.checkBox_321 = QtWidgets.QCheckBox(Form)
        self.checkBox_321.setText("")
        self.checkBox_321.setTristate(True)
        self.checkBox_321.setObjectName("checkBox_321")
        self.gridLayout1.addWidget(self.checkBox_321, 3, 4, 1, 1)
        self.checkBox_331 = QtWidgets.QCheckBox(Form)
        self.checkBox_331.setText("")
        self.checkBox_331.setTristate(True)
        self.checkBox_331.setObjectName("checkBox_331")
        self.gridLayout1.addWidget(self.checkBox_331, 3, 5, 1, 1)
        self.checkBox_341 = QtWidgets.QCheckBox(Form)
        self.checkBox_341.setText("")
        self.checkBox_341.setTristate(True)
        self.checkBox_341.setObjectName("checkBox_341")
        self.gridLayout1.addWidget(self.checkBox_341, 3, 6, 1, 1)
        self.checkBox_351 = QtWidgets.QCheckBox(Form)
        self.checkBox_351.setText("")
        self.checkBox_351.setTristate(True)
        self.checkBox_351.setObjectName("checkBox_351")
        self.gridLayout1.addWidget(self.checkBox_351, 3, 7, 1, 1)
        self.checkBox_361 = QtWidgets.QCheckBox(Form)
        self.checkBox_361.setText("")
        self.checkBox_361.setTristate(True)
        self.checkBox_361.setObjectName("checkBox_361")
        self.gridLayout1.addWidget(self.checkBox_361, 3, 8, 1, 1)
        self.checkBox_371 = QtWidgets.QCheckBox(Form)
        self.checkBox_371.setText("")
        self.checkBox_371.setTristate(True)
        self.checkBox_371.setObjectName("checkBox_371")
        self.gridLayout1.addWidget(self.checkBox_371, 3, 9, 1, 1)
        self.checkBox_381 = QtWidgets.QCheckBox(Form)
        self.checkBox_381.setText("")
        self.checkBox_381.setTristate(True)
        self.checkBox_381.setObjectName("checkBox_381")
        self.gridLayout1.addWidget(self.checkBox_381, 3, 10, 1, 1)
        self.checkBox_391 = QtWidgets.QCheckBox(Form)
        self.checkBox_391.setText("")
        self.checkBox_391.setTristate(True)
        self.checkBox_391.setObjectName("checkBox_391")
        self.gridLayout1.addWidget(self.checkBox_391, 4, 2, 1, 1)
        self.checkBox_401 = QtWidgets.QCheckBox(Form)
        self.checkBox_401.setText("")
        self.checkBox_401.setTristate(True)
        self.checkBox_401.setObjectName("checkBox_401")
        self.gridLayout1.addWidget(self.checkBox_401, 4, 3, 1, 1)
        self.checkBox_411 = QtWidgets.QCheckBox(Form)
        self.checkBox_411.setText("")
        self.checkBox_411.setTristate(True)
        self.checkBox_411.setObjectName("checkBox_411")
        self.gridLayout1.addWidget(self.checkBox_411, 4, 4, 1, 1)
        self.checkBox_421 = QtWidgets.QCheckBox(Form)
        self.checkBox_421.setText("")
        self.checkBox_421.setTristate(True)
        self.checkBox_421.setObjectName("checkBox_421")
        self.gridLayout1.addWidget(self.checkBox_421, 4, 5, 1, 1)
        self.checkBox_431 = QtWidgets.QCheckBox(Form)
        self.checkBox_431.setText("")
        self.checkBox_431.setTristate(True)
        self.checkBox_431.setObjectName("checkBox_431")
        self.gridLayout1.addWidget(self.checkBox_431, 4, 6, 1, 1)
        self.checkBox_441 = QtWidgets.QCheckBox(Form)
        self.checkBox_441.setText("")
        self.checkBox_441.setTristate(True)
        self.checkBox_441.setObjectName("checkBox_441")
        self.gridLayout1.addWidget(self.checkBox_441, 4, 7, 1, 1)
        self.checkBox_451 = QtWidgets.QCheckBox(Form)
        self.checkBox_451.setText("")
        self.checkBox_451.setTristate(True)
        self.checkBox_451.setObjectName("checkBox_451")
        self.gridLayout1.addWidget(self.checkBox_451, 4, 8, 1, 1)
        self.checkBox_461 = QtWidgets.QCheckBox(Form)
        self.checkBox_461.setText("")
        self.checkBox_461.setTristate(True)
        self.checkBox_461.setObjectName("checkBox_461")
        self.gridLayout1.addWidget(self.checkBox_461, 4, 9, 1, 1)
        self.checkBox_471 = QtWidgets.QCheckBox(Form)
        self.checkBox_471.setText("")
        self.checkBox_471.setTristate(True)
        self.checkBox_471.setObjectName("checkBox_471")
        self.gridLayout1.addWidget(self.checkBox_471, 4, 10, 1, 1)
        self.checkBox_141 = QtWidgets.QCheckBox(Form)
        self.checkBox_141.setText("")
        self.checkBox_141.setTristate(True)
        self.checkBox_141.setObjectName("checkBox_141")
        self.gridLayout1.addWidget(self.checkBox_141, 1, 4, 1, 1)
        self.checkBox_151 = QtWidgets.QCheckBox(Form)
        self.checkBox_151.setText("")
        self.checkBox_151.setTristate(True)
        self.checkBox_151.setObjectName("checkBox_151")
        self.gridLayout1.addWidget(self.checkBox_151, 1, 5, 1, 1)
        self.checkBox_161 = QtWidgets.QCheckBox(Form)
        self.checkBox_161.setText("")
        self.checkBox_161.setTristate(True)
        self.checkBox_161.setObjectName("checkBox_161")
        self.gridLayout1.addWidget(self.checkBox_161, 1, 6, 1, 1)
        self.checkBox_171 = QtWidgets.QCheckBox(Form)
        self.checkBox_171.setText("")
        self.checkBox_171.setTristate(True)
        self.checkBox_171.setObjectName("checkBox_171")
        self.gridLayout1.addWidget(self.checkBox_171, 1, 7, 1, 1)
        self.checkBox_181 = QtWidgets.QCheckBox(Form)
        self.checkBox_181.setText("")
        self.checkBox_181.setTristate(True)
        self.checkBox_181.setObjectName("checkBox_181")
        self.gridLayout1.addWidget(self.checkBox_181, 1, 8, 1, 1)
        self.checkBox_191 = QtWidgets.QCheckBox(Form)
        self.checkBox_191.setText("")
        self.checkBox_191.setTristate(True)
        self.checkBox_191.setObjectName("checkBox_191")
        self.gridLayout1.addWidget(self.checkBox_191, 1, 9, 1, 1)
        self.checkBox_201 = QtWidgets.QCheckBox(Form)
        self.checkBox_201.setText("")
        self.checkBox_201.setTristate(True)
        self.checkBox_201.setObjectName("checkBox_201")
        self.gridLayout1.addWidget(self.checkBox_201, 1, 10, 1, 1)
        self.checkBox_211 = QtWidgets.QCheckBox(Form)
        self.checkBox_211.setText("")
        self.checkBox_211.setTristate(True)
        self.checkBox_211.setObjectName("checkBox_211")
        self.gridLayout1.addWidget(self.checkBox_211, 2, 2, 1, 1)
        self.checkBox_221 = QtWidgets.QCheckBox(Form)
        self.checkBox_221.setText("")
        self.checkBox_221.setTristate(True)
        self.checkBox_221.setObjectName("checkBox_221")
        self.gridLayout1.addWidget(self.checkBox_221, 2, 3, 1, 1)
        self.checkBox_231 = QtWidgets.QCheckBox(Form)
        self.checkBox_231.setText("")
        self.checkBox_231.setTristate(True)
        self.checkBox_231.setObjectName("checkBox_231")
        self.gridLayout1.addWidget(self.checkBox_231, 2, 4, 1, 1)
        self.checkBox_241 = QtWidgets.QCheckBox(Form)
        self.checkBox_241.setText("")
        self.checkBox_241.setTristate(True)
        self.checkBox_241.setObjectName("checkBox_241")
        self.gridLayout1.addWidget(self.checkBox_241, 2, 5, 1, 1)
        self.checkBox_251 = QtWidgets.QCheckBox(Form)
        self.checkBox_251.setText("")
        self.checkBox_251.setTristate(True)
        self.checkBox_251.setObjectName("checkBox_251")
        self.gridLayout1.addWidget(self.checkBox_251, 2, 6, 1, 1)
        self.checkBox_261 = QtWidgets.QCheckBox(Form)
        self.checkBox_261.setText("")
        self.checkBox_261.setTristate(True)
        self.checkBox_261.setObjectName("checkBox_261")
        self.gridLayout1.addWidget(self.checkBox_261, 2, 7, 1, 1)
        self.checkBox_271 = QtWidgets.QCheckBox(Form)
        self.checkBox_271.setText("")
        self.checkBox_271.setTristate(True)
        self.checkBox_271.setObjectName("checkBox_271")
        self.gridLayout1.addWidget(self.checkBox_271, 2, 8, 1, 1)
        self.checkBox_281 = QtWidgets.QCheckBox(Form)
        self.checkBox_281.setText("")
        self.checkBox_281.setTristate(True)
        self.checkBox_281.setObjectName("checkBox_281")
        self.gridLayout1.addWidget(self.checkBox_281, 2, 9, 1, 1)
        self.checkBox_291 = QtWidgets.QCheckBox(Form)
        self.checkBox_291.setText("")
        self.checkBox_291.setTristate(True)
        self.checkBox_291.setObjectName("checkBox_291")
        self.gridLayout1.addWidget(self.checkBox_291, 2, 10, 1, 1)
        self.checkBox1 = QtWidgets.QCheckBox(Form)
        self.checkBox1.setText("")
        self.checkBox1.setTristate(True)
        self.checkBox1.setObjectName("checkBox1")
        self.gridLayout1.addWidget(self.checkBox1, 1, 1, 1, 1)
        self.checkBox_91 = QtWidgets.QCheckBox(Form)
        self.checkBox_91.setText("")
        self.checkBox_91.setTristate(True)
        self.checkBox_91.setObjectName("checkBox_91")
        self.gridLayout1.addWidget(self.checkBox_91, 8, 1, 1, 1)
        self.checkBox_101 = QtWidgets.QCheckBox(Form)
        self.checkBox_101.setText("")
        self.checkBox_101.setTristate(True)
        self.checkBox_101.setObjectName("checkBox_101")
        self.gridLayout1.addWidget(self.checkBox_101, 9, 1, 1, 1)
        self.checkBox_111 = QtWidgets.QCheckBox(Form)
        self.checkBox_111.setText("")
        self.checkBox_111.setTristate(True)
        self.checkBox_111.setObjectName("checkBox_111")
        self.gridLayout1.addWidget(self.checkBox_111, 10, 1, 1, 1)
        self.checkBox_121 = QtWidgets.QCheckBox(Form)
        self.checkBox_121.setText("")
        self.checkBox_121.setTristate(True)
        self.checkBox_121.setObjectName("checkBox_121")
        self.gridLayout1.addWidget(self.checkBox_121, 1, 2, 1, 1)
        self.checkBox_941 = QtWidgets.QCheckBox(Form)
        self.checkBox_941.setText("")
        self.checkBox_941.setTristate(True)
        self.checkBox_941.setObjectName("checkBox_941")
        self.gridLayout1.addWidget(self.checkBox_941, 5, 2, 1, 1)
        self.checkBox_951 = QtWidgets.QCheckBox(Form)
        self.checkBox_951.setText("")
        self.checkBox_951.setTristate(True)
        self.checkBox_951.setObjectName("checkBox_951")
        self.gridLayout1.addWidget(self.checkBox_951, 5, 3, 1, 1)
        self.checkBox_961 = QtWidgets.QCheckBox(Form)
        self.checkBox_961.setText("")
        self.checkBox_961.setTristate(True)
        self.checkBox_961.setObjectName("checkBox_961")
        self.gridLayout1.addWidget(self.checkBox_961, 5, 4, 1, 1)
        self.checkBox_971 = QtWidgets.QCheckBox(Form)
        self.checkBox_971.setText("")
        self.checkBox_971.setTristate(True)
        self.checkBox_971.setObjectName("checkBox_971")
        self.gridLayout1.addWidget(self.checkBox_971, 5, 5, 1, 1)
        self.checkBox_981 = QtWidgets.QCheckBox(Form)
        self.checkBox_981.setText("")
        self.checkBox_981.setTristate(True)
        self.checkBox_981.setObjectName("checkBox_981")
        self.gridLayout1.addWidget(self.checkBox_981, 5, 6, 1, 1)
        self.checkBox_991 = QtWidgets.QCheckBox(Form)
        self.checkBox_991.setText("")
        self.checkBox_991.setTristate(True)
        self.checkBox_991.setObjectName("checkBox_991")
        self.gridLayout1.addWidget(self.checkBox_991, 5, 7, 1, 1)
        self.checkBox_1001 = QtWidgets.QCheckBox(Form)
        self.checkBox_1001.setText("")
        self.checkBox_1001.setTristate(True)
        self.checkBox_1001.setObjectName("checkBox_1001")
        self.gridLayout1.addWidget(self.checkBox_1001, 5, 8, 1, 1)
        self.checkBox_1011 = QtWidgets.QCheckBox(Form)
        self.checkBox_1011.setText("")
        self.checkBox_1011.setTristate(True)
        self.checkBox_1011.setObjectName("checkBox_1011")
        self.gridLayout1.addWidget(self.checkBox_1011, 5, 9, 1, 1)
        self.checkBox_1021 = QtWidgets.QCheckBox(Form)
        self.checkBox_1021.setText("")
        self.checkBox_1021.setTristate(True)
        self.checkBox_1021.setObjectName("checkBox_1021")
        self.gridLayout1.addWidget(self.checkBox_1021, 5, 10, 1, 1)
        self.checkBox_1031 = QtWidgets.QCheckBox(Form)
        self.checkBox_1031.setText("")
        self.checkBox_1031.setTristate(True)
        self.checkBox_1031.setObjectName("checkBox_1031")
        self.gridLayout1.addWidget(self.checkBox_1031, 6, 2, 1, 1)
        self.checkBox_1041 = QtWidgets.QCheckBox(Form)
        self.checkBox_1041.setText("")
        self.checkBox_1041.setTristate(True)
        self.checkBox_1041.setObjectName("checkBox_1041")
        self.gridLayout1.addWidget(self.checkBox_1041, 6, 3, 1, 1)
        self.checkBox_1051 = QtWidgets.QCheckBox(Form)
        self.checkBox_1051.setText("")
        self.checkBox_1051.setTristate(True)
        self.checkBox_1051.setObjectName("checkBox_1051")
        self.gridLayout1.addWidget(self.checkBox_1051, 6, 4, 1, 1)
        self.checkBox_1061 = QtWidgets.QCheckBox(Form)
        self.checkBox_1061.setText("")
        self.checkBox_1061.setTristate(True)
        self.checkBox_1061.setObjectName("checkBox_1061")
        self.gridLayout1.addWidget(self.checkBox_1061, 6, 5, 1, 1)
        self.checkBox_1071 = QtWidgets.QCheckBox(Form)
        self.checkBox_1071.setText("")
        self.checkBox_1071.setTristate(True)
        self.checkBox_1071.setObjectName("checkBox_1071")
        self.gridLayout1.addWidget(self.checkBox_1071, 6, 6, 1, 1)
        self.checkBox_1081 = QtWidgets.QCheckBox(Form)
        self.checkBox_1081.setText("")
        self.checkBox_1081.setTristate(True)
        self.checkBox_1081.setObjectName("checkBox_1081")
        self.gridLayout1.addWidget(self.checkBox_1081, 6, 7, 1, 1)
        self.checkBox_1091 = QtWidgets.QCheckBox(Form)
        self.checkBox_1091.setText("")
        self.checkBox_1091.setTristate(True)
        self.checkBox_1091.setObjectName("checkBox_1091")
        self.gridLayout1.addWidget(self.checkBox_1091, 6, 8, 1, 1)
        self.checkBox_1101 = QtWidgets.QCheckBox(Form)
        self.checkBox_1101.setText("")
        self.checkBox_1101.setTristate(True)
        self.checkBox_1101.setObjectName("checkBox_1101")
        self.gridLayout1.addWidget(self.checkBox_1101, 6, 9, 1, 1)
        self.checkBox_1111 = QtWidgets.QCheckBox(Form)
        self.checkBox_1111.setText("")
        self.checkBox_1111.setTristate(True)
        self.checkBox_1111.setObjectName("checkBox_1111")
        self.gridLayout1.addWidget(self.checkBox_1111, 6, 10, 1, 1)
        self.checkBox_1121 = QtWidgets.QCheckBox(Form)
        self.checkBox_1121.setText("")
        self.checkBox_1121.setTristate(True)
        self.checkBox_1121.setObjectName("checkBox_1121")
        self.gridLayout1.addWidget(self.checkBox_1121, 7, 2, 1, 1)
        self.checkBox_1131 = QtWidgets.QCheckBox(Form)
        self.checkBox_1131.setText("")
        self.checkBox_1131.setTristate(True)
        self.checkBox_1131.setObjectName("checkBox_1131")
        self.gridLayout1.addWidget(self.checkBox_1131, 7, 3, 1, 1)
        self.checkBox_1141 = QtWidgets.QCheckBox(Form)
        self.checkBox_1141.setText("")
        self.checkBox_1141.setTristate(True)
        self.checkBox_1141.setObjectName("checkBox_1141")
        self.gridLayout1.addWidget(self.checkBox_1141, 7, 4, 1, 1)
        self.checkBox_1151 = QtWidgets.QCheckBox(Form)
        self.checkBox_1151.setText("")
        self.checkBox_1151.setTristate(True)
        self.checkBox_1151.setObjectName("checkBox_1151")
        self.gridLayout1.addWidget(self.checkBox_1151, 7, 5, 1, 1)
        self.checkBox_1161 = QtWidgets.QCheckBox(Form)
        self.checkBox_1161.setText("")
        self.checkBox_1161.setTristate(True)
        self.checkBox_1161.setObjectName("checkBox_1161")
        self.gridLayout1.addWidget(self.checkBox_1161, 7, 6, 1, 1)
        self.checkBox_1171 = QtWidgets.QCheckBox(Form)
        self.checkBox_1171.setText("")
        self.checkBox_1171.setTristate(True)
        self.checkBox_1171.setObjectName("checkBox_1171")
        self.gridLayout1.addWidget(self.checkBox_1171, 7, 7, 1, 1)
        self.checkBox_1181 = QtWidgets.QCheckBox(Form)
        self.checkBox_1181.setText("")
        self.checkBox_1181.setTristate(True)
        self.checkBox_1181.setObjectName("checkBox_1181")
        self.gridLayout1.addWidget(self.checkBox_1181, 7, 8, 1, 1)
        self.checkBox_1191 = QtWidgets.QCheckBox(Form)
        self.checkBox_1191.setText("")
        self.checkBox_1191.setTristate(True)
        self.checkBox_1191.setObjectName("checkBox_1191")
        self.gridLayout1.addWidget(self.checkBox_1191, 7, 9, 1, 1)
        self.checkBox_1201 = QtWidgets.QCheckBox(Form)
        self.checkBox_1201.setText("")
        self.checkBox_1201.setTristate(True)
        self.checkBox_1201.setObjectName("checkBox_1201")
        self.gridLayout1.addWidget(self.checkBox_1201, 7, 10, 1, 1)
        self.checkBox_1211 = QtWidgets.QCheckBox(Form)
        self.checkBox_1211.setText("")
        self.checkBox_1211.setTristate(True)
        self.checkBox_1211.setObjectName("checkBox_1211")
        self.gridLayout1.addWidget(self.checkBox_1211, 8, 2, 1, 1)
        self.checkBox_1221 = QtWidgets.QCheckBox(Form)
        self.checkBox_1221.setText("")
        self.checkBox_1221.setTristate(True)
        self.checkBox_1221.setObjectName("checkBox_1221")
        self.gridLayout1.addWidget(self.checkBox_1221, 8, 3, 1, 1)
        self.checkBox_1231 = QtWidgets.QCheckBox(Form)
        self.checkBox_1231.setText("")
        self.checkBox_1231.setTristate(True)
        self.checkBox_1231.setObjectName("checkBox_1231")
        self.gridLayout1.addWidget(self.checkBox_1231, 8, 4, 1, 1)
        self.checkBox_1241 = QtWidgets.QCheckBox(Form)
        self.checkBox_1241.setText("")
        self.checkBox_1241.setTristate(True)
        self.checkBox_1241.setObjectName("checkBox_1241")
        self.gridLayout1.addWidget(self.checkBox_1241, 8, 5, 1, 1)
        self.checkBox_1251 = QtWidgets.QCheckBox(Form)
        self.checkBox_1251.setText("")
        self.checkBox_1251.setTristate(True)
        self.checkBox_1251.setObjectName("checkBox_1251")
        self.gridLayout1.addWidget(self.checkBox_1251, 8, 6, 1, 1)
        self.checkBox_1261 = QtWidgets.QCheckBox(Form)
        self.checkBox_1261.setText("")
        self.checkBox_1261.setTristate(True)
        self.checkBox_1261.setObjectName("checkBox_1261")
        self.gridLayout1.addWidget(self.checkBox_1261, 8, 7, 1, 1)
        self.checkBox_1271 = QtWidgets.QCheckBox(Form)
        self.checkBox_1271.setText("")
        self.checkBox_1271.setTristate(True)
        self.checkBox_1271.setObjectName("checkBox_1271")
        self.gridLayout1.addWidget(self.checkBox_1271, 8, 8, 1, 1)
        self.checkBox_1281 = QtWidgets.QCheckBox(Form)
        self.checkBox_1281.setText("")
        self.checkBox_1281.setTristate(True)
        self.checkBox_1281.setObjectName("checkBox_1281")
        self.gridLayout1.addWidget(self.checkBox_1281, 8, 9, 1, 1)
        self.checkBox_1291 = QtWidgets.QCheckBox(Form)
        self.checkBox_1291.setText("")
        self.checkBox_1291.setTristate(True)
        self.checkBox_1291.setObjectName("checkBox_1291")
        self.gridLayout1.addWidget(self.checkBox_1291, 8, 10, 1, 1)
        self.checkBox_1301 = QtWidgets.QCheckBox(Form)
        self.checkBox_1301.setText("")
        self.checkBox_1301.setTristate(True)
        self.checkBox_1301.setObjectName("checkBox_1301")
        self.gridLayout1.addWidget(self.checkBox_1301, 9, 2, 1, 1)
        self.checkBox_1311 = QtWidgets.QCheckBox(Form)
        self.checkBox_1311.setText("")
        self.checkBox_1311.setTristate(True)
        self.checkBox_1311.setObjectName("checkBox_1311")
        self.gridLayout1.addWidget(self.checkBox_1311, 9, 3, 1, 1)
        self.checkBox_1321 = QtWidgets.QCheckBox(Form)
        self.checkBox_1321.setText("")
        self.checkBox_1321.setTristate(True)
        self.checkBox_1321.setObjectName("checkBox_1321")
        self.gridLayout1.addWidget(self.checkBox_1321, 9, 4, 1, 1)
        self.checkBox_1331 = QtWidgets.QCheckBox(Form)
        self.checkBox_1331.setText("")
        self.checkBox_1331.setTristate(True)
        self.checkBox_1331.setObjectName("checkBox_1331")
        self.gridLayout1.addWidget(self.checkBox_1331, 9, 5, 1, 1)
        self.checkBox_1341 = QtWidgets.QCheckBox(Form)
        self.checkBox_1341.setText("")
        self.checkBox_1341.setTristate(True)
        self.checkBox_1341.setObjectName("checkBox_1341")
        self.gridLayout1.addWidget(self.checkBox_1341, 9, 6, 1, 1)
        self.checkBox_1351 = QtWidgets.QCheckBox(Form)
        self.checkBox_1351.setText("")
        self.checkBox_1351.setTristate(True)
        self.checkBox_1351.setObjectName("checkBox_1351")
        self.gridLayout1.addWidget(self.checkBox_1351, 9, 7, 1, 1)
        self.checkBox_1361 = QtWidgets.QCheckBox(Form)
        self.checkBox_1361.setText("")
        self.checkBox_1361.setTristate(True)
        self.checkBox_1361.setObjectName("checkBox_1361")
        self.gridLayout1.addWidget(self.checkBox_1361, 9, 8, 1, 1)
        self.checkBox_1371 = QtWidgets.QCheckBox(Form)
        self.checkBox_1371.setText("")
        self.checkBox_1371.setTristate(True)
        self.checkBox_1371.setObjectName("checkBox_1371")
        self.gridLayout1.addWidget(self.checkBox_1371, 9, 9, 1, 1)
        self.checkBox_1381 = QtWidgets.QCheckBox(Form)
        self.checkBox_1381.setText("")
        self.checkBox_1381.setTristate(True)
        self.checkBox_1381.setObjectName("checkBox_1381")
        self.gridLayout1.addWidget(self.checkBox_1381, 9, 10, 1, 1)
        self.checkBox_1391 = QtWidgets.QCheckBox(Form)
        self.checkBox_1391.setText("")
        self.checkBox_1391.setTristate(True)
        self.checkBox_1391.setObjectName("checkBox_1391")
        self.gridLayout1.addWidget(self.checkBox_1391, 10, 2, 1, 1)
        self.checkBox_1401 = QtWidgets.QCheckBox(Form)
        self.checkBox_1401.setText("")
        self.checkBox_1401.setTristate(True)
        self.checkBox_1401.setObjectName("checkBox_1401")
        self.gridLayout1.addWidget(self.checkBox_1401, 10, 3, 1, 1)
        self.checkBox_1411 = QtWidgets.QCheckBox(Form)
        self.checkBox_1411.setText("")
        self.checkBox_1411.setTristate(True)
        self.checkBox_1411.setObjectName("checkBox_1411")
        self.gridLayout1.addWidget(self.checkBox_1411, 10, 4, 1, 1)
        self.checkBox_1421 = QtWidgets.QCheckBox(Form)
        self.checkBox_1421.setText("")
        self.checkBox_1421.setTristate(True)
        self.checkBox_1421.setObjectName("checkBox_1421")
        self.gridLayout1.addWidget(self.checkBox_1421, 10, 5, 1, 1)
        self.checkBox_1431 = QtWidgets.QCheckBox(Form)
        self.checkBox_1431.setText("")
        self.checkBox_1431.setTristate(True)
        self.checkBox_1431.setObjectName("checkBox_1431")
        self.gridLayout1.addWidget(self.checkBox_1431, 10, 6, 1, 1)
        self.checkBox_1441 = QtWidgets.QCheckBox(Form)
        self.checkBox_1441.setText("")
        self.checkBox_1441.setTristate(True)
        self.checkBox_1441.setObjectName("checkBox_1441")
        self.gridLayout1.addWidget(self.checkBox_1441, 10, 7, 1, 1)
        self.checkBox_1451 = QtWidgets.QCheckBox(Form)
        self.checkBox_1451.setText("")
        self.checkBox_1451.setTristate(True)
        self.checkBox_1451.setObjectName("checkBox_1451")
        self.gridLayout1.addWidget(self.checkBox_1451, 10, 8, 1, 1)
        self.checkBox_1461 = QtWidgets.QCheckBox(Form)
        self.checkBox_1461.setText("")
        self.checkBox_1461.setTristate(True)
        self.checkBox_1461.setObjectName("checkBox_1461")
        self.gridLayout1.addWidget(self.checkBox_1461, 10, 9, 1, 1)
        self.checkBox_1471 = QtWidgets.QCheckBox(Form)
        self.checkBox_1471.setText("")
        self.checkBox_1471.setTristate(True)
        self.checkBox_1471.setObjectName("checkBox_1471")
        self.gridLayout1.addWidget(self.checkBox_1471, 10, 10, 1, 1)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout1.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_24.setObjectName("label_24")
        self.gridLayout1.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout1.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout1.addWidget(self.label_27, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout1.addWidget(self.label_28, 0, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout1.addWidget(self.label_29, 0, 5, 1, 1)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout1.addWidget(self.label_30, 0, 6, 1, 1)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout1.addWidget(self.label_31, 0, 7, 1, 1)
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout1.addWidget(self.label_32, 0, 8, 1, 1)
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout1.addWidget(self.label_33, 0, 9, 1, 1)
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout1.addWidget(self.label_34, 0, 10, 1, 1)
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_35.setObjectName("label_35")
        self.gridLayout1.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_36.setObjectName("label_36")
        self.gridLayout1.addWidget(self.label_36, 3, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_37.setObjectName("label_37")
        self.gridLayout1.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(Form)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_38.setObjectName("label_38")
        self.gridLayout1.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(Form)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_39.setObjectName("label_39")
        self.gridLayout1.addWidget(self.label_39, 6, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(Form)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_40.setObjectName("label_40")
        self.gridLayout1.addWidget(self.label_40, 7, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_41.setObjectName("label_41")
        self.gridLayout1.addWidget(self.label_41, 8, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(Form)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_42.setObjectName("label_42")
        self.gridLayout1.addWidget(self.label_42, 9, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(Form)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_43.setObjectName("label_43")
        self.gridLayout1.addWidget(self.label_43, 10, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "BattleShip"))
        self.Player1_name.setText(_translate("Form", "Player 1"))
        self.label_5.setText(_translate("Form", "2"))
        self.label_4.setText(_translate("Form", "1"))
        self.label_11.setText(_translate("Form", "8"))
        self.label_10.setText(_translate("Form", "7"))
        self.label_8.setText(_translate("Form", "5"))
        self.label_6.setText(_translate("Form", "3"))
        self.label_7.setText(_translate("Form", "4"))
        self.label_9.setText(_translate("Form", "6"))
        self.label_12.setText(_translate("Form", "9"))
        self.label_13.setText(_translate("Form", "10"))
        self.label_14.setText(_translate("Form", "A"))
        self.label_15.setText(_translate("Form", "B"))
        self.label_16.setText(_translate("Form", "C"))
        self.label_17.setText(_translate("Form", "D"))
        self.label_18.setText(_translate("Form", "E"))
        self.label_19.setText(_translate("Form", "F"))
        self.label_20.setText(_translate("Form", "G"))
        self.label_21.setText(_translate("Form", "H"))
        self.label_22.setText(_translate("Form", "I"))
        self.label_23.setText(_translate("Form", "J"))
        self.Player2_name.setText(_translate("Form", "Player 2"))
        self.label_25.setText(_translate("Form", "1"))
        self.label_24.setText(_translate("Form", "A"))
        self.label_26.setText(_translate("Form", "2"))
        self.label_27.setText(_translate("Form", "3"))
        self.label_28.setText(_translate("Form", "4"))
        self.label_29.setText(_translate("Form", "5"))
        self.label_30.setText(_translate("Form", "6"))
        self.label_31.setText(_translate("Form", "7"))
        self.label_32.setText(_translate("Form", "8"))
        self.label_33.setText(_translate("Form", "9"))
        self.label_34.setText(_translate("Form", "10"))
        self.label_35.setText(_translate("Form", "B"))
        self.label_36.setText(_translate("Form", "C"))
        self.label_37.setText(_translate("Form", "D"))
        self.label_38.setText(_translate("Form", "E"))
        self.label_39.setText(_translate("Form", "F"))
        self.label_40.setText(_translate("Form", "G"))
        self.label_41.setText(_translate("Form", "H"))
        self.label_42.setText(_translate("Form", "I"))
        self.label_43.setText(_translate("Form", "J"))

